package com.generator.mapper;

import com.generator.pojo.CartonSupplier;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    int insert(CartonSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    int insertSelective(CartonSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    CartonSupplier selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartonSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_supplier
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartonSupplier record);

    List<CartonSupplier> selects();

    List<CartonSupplier> dropSelect(@Param(value = "q") String q);
}