package com.generator.mapper;

import com.generator.pojo.CartonOutInfo;
import com.generator.pojo.Cartonout;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    int insert(Cartonout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    int insertSelective(Cartonout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    Cartonout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cartonout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonOut
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cartonout record);

    List<Cartonout> selectByNum(String deliveryNumber);

    int updataByD(@Param(value="list")List<Cartonout> list);

    List<Cartonout> selectByD(@Param(value="deliveryNumber")String deliveryNumber);

    List<Cartonout> selectByTopjui(@Param(value="orderAccount")String orderAccount);

    List<Cartonout> selectByCus(@Param(value="list")List<CartonOutInfo> list);

    int addCO(@Param(value="list")List<Cartonout> list);

    List<Cartonout> selectDui(@Param(value="custom")String custom, @Param(value="stratime")String stratime,@Param(value="endtime") String endtime);

    List<Cartonout> selectByNums(String[] deliveryNumber);

    //List<Cartonout> selectByDnumber(@Param(value="deliveryNumber")String deliveryNumber);


}