package com.generator.mapper;

import com.generator.pojo.CartonRecord;
import com.generator.pojo.ComplexQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    int insert(CartonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    int insertSelective(CartonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    CartonRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartonRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartonRecord record);

    List<CartonRecord>selectAl(@Param("cur") int cur, @Param("rows") int rows, @Param("sort") String sort, @Param("order") String order, @Param("list") List<ComplexQuery> queryList, @Param("startTime") String startTime, @Param("endTime") String endTime);

    List<CartonRecord> selectAll( @Param("list") List<ComplexQuery> queryList, @Param("startTime") String startTime, @Param("endTime") String endTime);

    CartonRecord findById(@Param(value = "orderNumber") String orderNumber);
}