package com.generator.mapper;

import com.generator.pojo.CartonOutInfo;
import com.generator.pojo.Cartonwarehousing;
import com.generator.pojo.StorageLabel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonwarehousingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    int insert(Cartonwarehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    int insertSelective(Cartonwarehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    Cartonwarehousing selectByPrimaryKey(Integer rkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cartonwarehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonWarehousing
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cartonwarehousing record);

    List<Cartonwarehousing>selectByRu(@Param(value = "orderAccount")String orderAccount);

    Cartonwarehousing findByMaxAccount(@Param(value = "time")String time);

    List<Cartonwarehousing> getListByPurId(int[] rk);
}