package com.generator.mapper;

import com.generator.pojo.CartonFormula;
import com.generator.pojo.CartonPitRelation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonPitRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    int insert(CartonPitRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    int insertSelective(CartonPitRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    CartonPitRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartonPitRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carton_pit_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartonPitRelation record);

    /**
     * 批量添加箱型楞型关系
     * @param list
     * @return
     */
    int addRelatinS(List<CartonPitRelation> list);

    /**
     * 通过箱型id和楞型id查询出系数
     * @param integer
     * @param integer1
     * @return
     */
    CartonPitRelation findRelation(@Param("integer") Integer integer,@Param("integer1") Integer integer1);

    /**
     * 通过箱型id加载出该箱型的所有楞型系数  分页查询
     * @param cur
     * @param rows
     * @param integer
     * @return
     */
    List<CartonPitRelation> findByCartonId(@Param("cur") int cur,@Param("rows") int rows,@Param("integer") Integer integer);

    /**
     * 通过箱型id加载出该箱型的所有楞型系数  查询全部
     * @param integer
     * @return
     */
    List<CartonPitRelation> findByCartonIdAll(@Param("integer") Integer integer);

    /**
     * 批量删除箱型楞型关系表
     * @param list
     * @return
     */
    int deleteBatchCarPit(List<CartonFormula> list);

    /**
     * 删除箱型楞型关系镖中的数据
     * @param i
     * @return
     */
    int deleteByPitId(@Param("i") int i);
}