package com.generator.mapper;

import com.generator.pojo.CartonplantModel2;
import com.generator.pojo.ComplexQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartonplantModel2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cartonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    int insert(CartonplantModel2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    int insertSelective(CartonplantModel2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    CartonplantModel2 selectByPrimaryKey(Integer cartonId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartonplantModel2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartonplant_model2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartonplantModel2 record);

    List<CartonplantModel2> select(@Param("cur") int cur,@Param("rows") int rows,@Param("sort") String sort,@Param("oder") String oder,@Param("list") List<ComplexQuery> queryList);

    List<CartonplantModel2> selectAll(@Param("list") List<ComplexQuery> queryList);

    /**
     * 产品下拉框查询
     * @param q
     * @return
     */
    List<CartonplantModel2> dropSelect(@Param("q") String q);

    /**
     * 查找出有该楞型的产品
     * @param i
     * @return
     */
    List<CartonplantModel2> findByPitId(@Param("i") int i);
}