package com.generator.mapper;

import com.generator.pojo.CompanyInformation;
import com.generator.pojo.ComplexQuery;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CompanyInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    int insert(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    int insertSelective(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    CompanyInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyInformation record);

    /**
     * 查询列表 分页
     * @param cur
     * @param rows
     * @param queryList
     * @return
     */
    List<CompanyInformation> findList(@Param("cur") int cur,@Param("rows") int rows,@Param("list") List<ComplexQuery> queryList);

    /**
     * 查询列表 全部
     * @param queryList
     * @return
     */
    List<CompanyInformation> findListAll(List<ComplexQuery> queryList);

    /**
     * 删除公司信息 可批量
     * @param list
     * @return
     */
    int deleteCompanyInformation(List<CompanyInformation> list);

    /**
     * 下拉框
     * @param q
     * @return
     */
    List<CompanyInformation> select(@Param(value = "q") String q);

    List<CompanyInformation> findByIds(int[] coids);
}