package com.generator.mapper;

import com.generator.pojo.CopeWith;

public interface CopeWithMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    int insert(CopeWith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    int insertSelective(CopeWith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    CopeWith selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CopeWith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cope_with
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CopeWith record);
}