package com.generator.mapper;

import com.generator.pojo.DeliPeople;

public interface DeliPeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer deliId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    int insert(DeliPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    int insertSelective(DeliPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    DeliPeople selectByPrimaryKey(Integer deliId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeliPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deli_people
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeliPeople record);
}