package com.generator.mapper;

import com.generator.pojo.ComplexQuery;
import com.generator.pojo.Duizhang;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DuizhangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    int insert(Duizhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    int insertSelective(Duizhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    Duizhang selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Duizhang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duizhang
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Duizhang record);

    List<Duizhang> getList();

    Duizhang findById(@Param(value = "id")int id);

    List<Duizhang> selectAll(List<ComplexQuery> queryList);

    List<Duizhang> select(@Param(value = "cur")int cur, @Param(value = "rows")int rows, @Param(value = "sort")String sort, @Param(value = "oder")String oder, @Param(value = "list")List<ComplexQuery> queryList);

    List<Duizhang> dropSelect(@Param(value = "q")String q);
}