package com.generator.mapper;

import com.generator.pojo.ComplexQuery;
import com.generator.pojo.FinancialRegistration;
import com.generator.pojo.ReceiptRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FinancialRegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer financialRegistrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    int insert(FinancialRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    int insertSelective(FinancialRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    FinancialRegistration selectByPrimaryKey(Integer financialRegistrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinancialRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinancialRegistration record);

    List<FinancialRegistration> select(@Param("cur") int cur,@Param("rows") int rows,@Param("sort") String sort,@Param("order") String order,@Param("list") List<ComplexQuery> queryList,@Param("startTime") String startTime,@Param("endTime") String endTime);

    List<FinancialRegistration> selectAll(@Param("list") List<ComplexQuery> queryList,@Param("startTime") String startTime,@Param("endTime") String endTime);
}