package com.generator.mapper;

import com.generator.pojo.Flut;

import java.util.List;

public interface FlutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    int insert(Flut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    int insertSelective(Flut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    Flut selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Flut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flut
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Flut record);

    List<Flut> select();

}