package com.generator.mapper;

import com.generator.pojo.MakingStock;

public interface MakingStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    int insert(MakingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    int insertSelective(MakingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    MakingStock selectByPrimaryKey(Integer stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MakingStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table making_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MakingStock record);
}