package com.generator.mapper;

import com.generator.pojo.MaterialStorage;

public interface MaterialStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer makingStorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    int insert(MaterialStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    int insertSelective(MaterialStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    MaterialStorage selectByPrimaryKey(Integer makingStorageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MaterialStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_storage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaterialStorage record);
}