package com.generator.mapper;

import com.generator.pojo.Onemenu;

public interface OnemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    int insert(Onemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    int insertSelective(Onemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    Onemenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Onemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onemenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Onemenu record);
}