package com.generator.mapper;

import com.generator.pojo.PaperA;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaperAMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    int insert(PaperA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    int insertSelective(PaperA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    PaperA selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaperA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_a
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaperA record);

    List<PaperA> selectById(@Param(value = "id") int id,@Param(value = "cur") int cur,@Param(value = "rows") int rows);

    List<PaperA> findAll(int id);

    String findMyCode(@Param(value = "supllierId")int supllierId,@Param(value ="str")String str);
}