package com.generator.mapper;

import com.generator.pojo.ComplexQuery;
import com.generator.pojo.PaymenttRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymenttRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer paymentRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    int insert(PaymenttRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    int insertSelective(PaymenttRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    PaymenttRecord selectByPrimaryKey(Integer paymentRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymenttRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentt_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymenttRecord record);

    List<PaymenttRecord> select(@Param("cur") int cur, @Param("rows") int rows, @Param("sort") String sort, @Param("order") String order, @Param("list") List<ComplexQuery> queryList, @Param("startTime") String startTime, @Param("endTime") String endTime);

    List<PaymenttRecord> selectAll(@Param("list") List<ComplexQuery> queryList,@Param("startTime") String startTime,@Param("endTime") String endTime);
}