package com.generator.mapper;

import com.generator.pojo.ProcessCost;

public interface ProcessCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer processCostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    int insert(ProcessCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    int insertSelective(ProcessCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    ProcessCost selectByPrimaryKey(Integer processCostId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProcessCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_cost
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProcessCost record);
}