package com.generator.mapper;

import com.generator.pojo.ComplexQuery;
import com.generator.pojo.Rejected;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RejectedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rejectedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    int insert(Rejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    int insertSelective(Rejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    Rejected selectByPrimaryKey(Integer rejectedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rejected record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rejected
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rejected record);

    List<Rejected> select(@Param("cur") int cur, @Param("rows") int rows, @Param("sort") String sort, @Param("oder") String oder, @Param("list")  List<ComplexQuery> queryList);

    List<Rejected> selectAll(@Param("list") List<ComplexQuery> queryList);
}