package com.generator.mapper;

import com.generator.pojo.ComplexQuery;
import com.generator.pojo.StaffTable;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    int insert(StaffTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    int insertSelective(StaffTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    StaffTable selectByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaffTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffTable record);


    List<StaffTable> selectAll();


    StaffTable selectById(int staffid);

    List<StaffTable> selects();

    List<StaffTable> dropSelect(String q);

    List<StaffTable> selectd(@Param("cur") int cur, @Param("rows") int rows, @Param("sort") String sort, @Param("oder") String oder,@Param("list")  List<ComplexQuery> queryList);

    List<StaffTable> selectAlld(@Param("list") List<ComplexQuery> queryList);

    /**
     * 业务员下拉框查询
     * @param q
     * @return
     */
    List<StaffTable> findByBusiness(@Param("q") String q,@Param("type") int type);

    StaffTable staffTableBystaffNumber();
}