package com.generator.mapper;

import com.generator.pojo.SupplierEquipment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupplierEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    int insert(SupplierEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    int insertSelective(SupplierEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    SupplierEquipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplierEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_equipment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierEquipment record);


    List<SupplierEquipment> selectById(@Param(value = "id") int id,@Param(value = "cur")int cur,@Param(value = "rows") int rows);

    List<SupplierEquipment> findAll(@Param(value = "id") int id);
}