package com.generator.mapper;

import com.generator.pojo.SupplierMaterialb;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupplierMaterialbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    int insert(SupplierMaterialb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    int insertSelective(SupplierMaterialb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    SupplierMaterialb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplierMaterialb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materialB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierMaterialb record);
    List<SupplierMaterialb> selectById(@Param(value = "id") int id,@Param(value = "cur") int cur,@Param(value = "rows") int rows);

    List<SupplierMaterialb> findByAll(@Param(value = "id")int id);

    SupplierMaterialb findByMaterialb(@Param(value = "id")int id,@Param(value = "myCode")String myCode);

    /**
     * 批量删除
     * @param list
     * @return
     */
    int batchDeleteSupplierB(List<SupplierMaterialb> list);
}