package com.generator.mapper;

import com.generator.pojo.Tremenu;

import java.util.List;

public interface TremenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    int insert(Tremenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    int insertSelective(Tremenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    Tremenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tremenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tremenu record);


    List<Tremenu> findTremenu(int pid);
}