package com.generator.mapper;

import com.generator.pojo.Twomenu;

import java.util.List;

public interface TwomenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    int insert(Twomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    int insertSelective(Twomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    Twomenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Twomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twoMenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Twomenu record);

    List<Twomenu> selectByPid(Integer pid);
}