package com.generator.mapper;

import com.generator.pojo.UpdateOperation;

public interface UpdateOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_operation
     *
     * @mbggenerated
     */
    int insert(UpdateOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_operation
     *
     * @mbggenerated
     */
    int insertSelective(UpdateOperation record);
}