package com.generator.pojo;

public class CartonPurKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_pur.pur_id
     *
     * @mbggenerated
     */
    private Integer purId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_pur.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_pur.pur_id
     *
     * @return the value of carton_pur.pur_id
     *
     * @mbggenerated
     */
    public Integer getPurId() {
        return purId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_pur.pur_id
     *
     * @param purId the value for carton_pur.pur_id
     *
     * @mbggenerated
     */
    public void setPurId(Integer purId) {
        this.purId = purId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_pur.order_id
     *
     * @return the value of carton_pur.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_pur.order_id
     *
     * @param orderId the value for carton_pur.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}