package com.generator.pojo;

public class CartonSupplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.abbreviation
     *
     * @mbggenerated
     */
    private String abbreviation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.shorthand_code
     *
     * @mbggenerated
     */
    private String shorthandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.supplier_type
     *
     * @mbggenerated
     */
    private Integer supplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.clearing_unit
     *
     * @mbggenerated
     */
    private String clearingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.supplier_address
     *
     * @mbggenerated
     */
    private String supplierAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.supplier_tel
     *
     * @mbggenerated
     */
    private String supplierTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.opening_bank
     *
     * @mbggenerated
     */
    private String openingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.account_number
     *
     * @mbggenerated
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.recognition_number
     *
     * @mbggenerated
     */
    private String recognitionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.max_width
     *
     * @mbggenerated
     */
    private Integer maxWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.max_length
     *
     * @mbggenerated
     */
    private Integer maxLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.min_width
     *
     * @mbggenerated
     */
    private Integer minWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.min_length
     *
     * @mbggenerated
     */
    private Integer minLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.stripe_number
     *
     * @mbggenerated
     */
    private Integer stripeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.flute_type
     *
     * @mbggenerated
     */
    private String fluteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.payment_method
     *
     * @mbggenerated
     */
    private Integer paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.cust
     *
     * @mbggenerated
     */
    private String cust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.tw
     *
     * @mbggenerated
     */
    private Double tw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.fc
     *
     * @mbggenerated
     */
    private Double fc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.ec
     *
     * @mbggenerated
     */
    private Double ec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.sc
     *
     * @mbggenerated
     */
    private Double sc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.vc
     *
     * @mbggenerated
     */
    private Double vc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.tc
     *
     * @mbggenerated
     */
    private Double tc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.ty
     *
     * @mbggenerated
     */
    private Double ty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.fy
     *
     * @mbggenerated
     */
    private Double fy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.sy
     *
     * @mbggenerated
     */
    private Double sy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.fi
     *
     * @mbggenerated
     */
    private Double fi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.si
     *
     * @mbggenerated
     */
    private Double si;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.se
     *
     * @mbggenerated
     */
    private Double se;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carton_supplier.zk
     *
     * @mbggenerated
     */
    private Integer zk;

    private String isheshui;


    private String cardPreferences;


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    private String name;

     private double offer;

    public double getOffer() {
        return offer;
    }

    public void setOffer(double offer) {
        this.offer = offer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.supplier_id
     *
     * @return the value of carton_supplier.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.supplier_id
     *
     * @param supplierId the value for carton_supplier.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.supplier_name
     *
     * @return the value of carton_supplier.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.supplier_name
     *
     * @param supplierName the value for carton_supplier.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.abbreviation
     *
     * @return the value of carton_supplier.abbreviation
     *
     * @mbggenerated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.abbreviation
     *
     * @param abbreviation the value for carton_supplier.abbreviation
     *
     * @mbggenerated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.shorthand_code
     *
     * @return the value of carton_supplier.shorthand_code
     *
     * @mbggenerated
     */
    public String getShorthandCode() {
        return shorthandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.shorthand_code
     *
     * @param shorthandCode the value for carton_supplier.shorthand_code
     *
     * @mbggenerated
     */
    public void setShorthandCode(String shorthandCode) {
        this.shorthandCode = shorthandCode == null ? null : shorthandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.supplier_type
     *
     * @return the value of carton_supplier.supplier_type
     *
     * @mbggenerated
     */
    public Integer getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.supplier_type
     *
     * @param supplierType the value for carton_supplier.supplier_type
     *
     * @mbggenerated
     */
    public void setSupplierType(Integer supplierType) {
        this.supplierType = supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.clearing_unit
     *
     * @return the value of carton_supplier.clearing_unit
     *
     * @mbggenerated
     */
    public String getClearingUnit() {
        return clearingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.clearing_unit
     *
     * @param clearingUnit the value for carton_supplier.clearing_unit
     *
     * @mbggenerated
     */
    public void setClearingUnit(String clearingUnit) {
        this.clearingUnit = clearingUnit == null ? null : clearingUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.supplier_address
     *
     * @return the value of carton_supplier.supplier_address
     *
     * @mbggenerated
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.supplier_address
     *
     * @param supplierAddress the value for carton_supplier.supplier_address
     *
     * @mbggenerated
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress == null ? null : supplierAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.supplier_tel
     *
     * @return the value of carton_supplier.supplier_tel
     *
     * @mbggenerated
     */
    public String getSupplierTel() {
        return supplierTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.supplier_tel
     *
     * @param supplierTel the value for carton_supplier.supplier_tel
     *
     * @mbggenerated
     */
    public void setSupplierTel(String supplierTel) {
        this.supplierTel = supplierTel == null ? null : supplierTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.opening_bank
     *
     * @return the value of carton_supplier.opening_bank
     *
     * @mbggenerated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.opening_bank
     *
     * @param openingBank the value for carton_supplier.opening_bank
     *
     * @mbggenerated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.account_number
     *
     * @return the value of carton_supplier.account_number
     *
     * @mbggenerated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.account_number
     *
     * @param accountNumber the value for carton_supplier.account_number
     *
     * @mbggenerated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.fax
     *
     * @return the value of carton_supplier.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.fax
     *
     * @param fax the value for carton_supplier.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.recognition_number
     *
     * @return the value of carton_supplier.recognition_number
     *
     * @mbggenerated
     */
    public String getRecognitionNumber() {
        return recognitionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.recognition_number
     *
     * @param recognitionNumber the value for carton_supplier.recognition_number
     *
     * @mbggenerated
     */
    public void setRecognitionNumber(String recognitionNumber) {
        this.recognitionNumber = recognitionNumber == null ? null : recognitionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.max_width
     *
     * @return the value of carton_supplier.max_width
     *
     * @mbggenerated
     */
    public Integer getMaxWidth() {
        return maxWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.max_width
     *
     * @param maxWidth the value for carton_supplier.max_width
     *
     * @mbggenerated
     */
    public void setMaxWidth(Integer maxWidth) {
        this.maxWidth = maxWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.max_length
     *
     * @return the value of carton_supplier.max_length
     *
     * @mbggenerated
     */
    public Integer getMaxLength() {
        return maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.max_length
     *
     * @param maxLength the value for carton_supplier.max_length
     *
     * @mbggenerated
     */
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.min_width
     *
     * @return the value of carton_supplier.min_width
     *
     * @mbggenerated
     */
    public Integer getMinWidth() {
        return minWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.min_width
     *
     * @param minWidth the value for carton_supplier.min_width
     *
     * @mbggenerated
     */
    public void setMinWidth(Integer minWidth) {
        this.minWidth = minWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.min_length
     *
     * @return the value of carton_supplier.min_length
     *
     * @mbggenerated
     */
    public Integer getMinLength() {
        return minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.min_length
     *
     * @param minLength the value for carton_supplier.min_length
     *
     * @mbggenerated
     */
    public void setMinLength(Integer minLength) {
        this.minLength = minLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.unit
     *
     * @return the value of carton_supplier.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.unit
     *
     * @param unit the value for carton_supplier.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.stripe_number
     *
     * @return the value of carton_supplier.stripe_number
     *
     * @mbggenerated
     */
    public Integer getStripeNumber() {
        return stripeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.stripe_number
     *
     * @param stripeNumber the value for carton_supplier.stripe_number
     *
     * @mbggenerated
     */
    public void setStripeNumber(Integer stripeNumber) {
        this.stripeNumber = stripeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.flute_type
     *
     * @return the value of carton_supplier.flute_type
     *
     * @mbggenerated
     */
    public String getFluteType() {
        return fluteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.flute_type
     *
     * @param fluteType the value for carton_supplier.flute_type
     *
     * @mbggenerated
     */
    public void setFluteType(String fluteType) {
        this.fluteType = fluteType == null ? null : fluteType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.payment_method
     *
     * @return the value of carton_supplier.payment_method
     *
     * @mbggenerated
     */
    public Integer getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.payment_method
     *
     * @param paymentMethod the value for carton_supplier.payment_method
     *
     * @mbggenerated
     */
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.fake
     *
     * @return the value of carton_supplier.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.fake
     *
     * @param fake the value for carton_supplier.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.cust
     *
     * @return the value of carton_supplier.cust
     *
     * @mbggenerated
     */
    public String getCust() {
        return cust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.cust
     *
     * @param cust the value for carton_supplier.cust
     *
     * @mbggenerated
     */
    public void setCust(String cust) {
        this.cust = cust == null ? null : cust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.tw
     *
     * @return the value of carton_supplier.tw
     *
     * @mbggenerated
     */
    public Double getTw() {
        return tw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.tw
     *
     * @param tw the value for carton_supplier.tw
     *
     * @mbggenerated
     */
    public void setTw(Double tw) {
        this.tw = tw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.fc
     *
     * @return the value of carton_supplier.fc
     *
     * @mbggenerated
     */
    public Double getFc() {
        return fc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.fc
     *
     * @param fc the value for carton_supplier.fc
     *
     * @mbggenerated
     */
    public void setFc(Double fc) {
        this.fc = fc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.ec
     *
     * @return the value of carton_supplier.ec
     *
     * @mbggenerated
     */
    public Double getEc() {
        return ec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.ec
     *
     * @param ec the value for carton_supplier.ec
     *
     * @mbggenerated
     */
    public void setEc(Double ec) {
        this.ec = ec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.sc
     *
     * @return the value of carton_supplier.sc
     *
     * @mbggenerated
     */
    public Double getSc() {
        return sc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.sc
     *
     * @param sc the value for carton_supplier.sc
     *
     * @mbggenerated
     */
    public void setSc(Double sc) {
        this.sc = sc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.vc
     *
     * @return the value of carton_supplier.vc
     *
     * @mbggenerated
     */
    public Double getVc() {
        return vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.vc
     *
     * @param vc the value for carton_supplier.vc
     *
     * @mbggenerated
     */
    public void setVc(Double vc) {
        this.vc = vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.tc
     *
     * @return the value of carton_supplier.tc
     *
     * @mbggenerated
     */
    public Double getTc() {
        return tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.tc
     *
     * @param tc the value for carton_supplier.tc
     *
     * @mbggenerated
     */
    public void setTc(Double tc) {
        this.tc = tc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.ty
     *
     * @return the value of carton_supplier.ty
     *
     * @mbggenerated
     */
    public Double getTy() {
        return ty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.ty
     *
     * @param ty the value for carton_supplier.ty
     *
     * @mbggenerated
     */
    public void setTy(Double ty) {
        this.ty = ty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.fy
     *
     * @return the value of carton_supplier.fy
     *
     * @mbggenerated
     */
    public Double getFy() {
        return fy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.fy
     *
     * @param fy the value for carton_supplier.fy
     *
     * @mbggenerated
     */
    public void setFy(Double fy) {
        this.fy = fy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.sy
     *
     * @return the value of carton_supplier.sy
     *
     * @mbggenerated
     */
    public Double getSy() {
        return sy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.sy
     *
     * @param sy the value for carton_supplier.sy
     *
     * @mbggenerated
     */
    public void setSy(Double sy) {
        this.sy = sy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.fi
     *
     * @return the value of carton_supplier.fi
     *
     * @mbggenerated
     */
    public Double getFi() {
        return fi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.fi
     *
     * @param fi the value for carton_supplier.fi
     *
     * @mbggenerated
     */
    public void setFi(Double fi) {
        this.fi = fi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.si
     *
     * @return the value of carton_supplier.si
     *
     * @mbggenerated
     */
    public Double getSi() {
        return si;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.si
     *
     * @param si the value for carton_supplier.si
     *
     * @mbggenerated
     */
    public void setSi(Double si) {
        this.si = si;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.se
     *
     * @return the value of carton_supplier.se
     *
     * @mbggenerated
     */
    public Double getSe() {
        return se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.se
     *
     * @param se the value for carton_supplier.se
     *
     * @mbggenerated
     */
    public void setSe(Double se) {
        this.se = se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.zk
     *
     * @return the value of carton_supplier.zk
     *
     * @mbggenerated
     */
    public Integer getZk() {
        return zk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.zk
     *
     * @param zk the value for carton_supplier.zk
     *
     * @mbggenerated
     */
    public void setZk(Integer zk) {
        this.zk = zk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.isheshui
     *
     * @return the value of carton_supplier.isheshui
     *
     * @mbggenerated
     */
    public String getIsheshui() {
        return isheshui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.isheshui
     *
     * @param isheshui the value for carton_supplier.isheshui
     *
     * @mbggenerated
     */
    public void setIsheshui(String isheshui) {
        this.isheshui = isheshui == null ? null : isheshui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carton_supplier.card_preferences
     *
     * @return the value of carton_supplier.card_preferences
     *
     * @mbggenerated
     */
    public String getCardPreferences() {
        return cardPreferences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carton_supplier.card_preferences
     *
     * @param cardPreferences the value for carton_supplier.card_preferences
     *
     * @mbggenerated
     */
    public void setCardPreferences(String cardPreferences) {
        this.cardPreferences = cardPreferences == null ? null : cardPreferences.trim();
    }
}