package com.generator.pojo;

import java.util.List;

public class Cartonout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.delivery_number
     *
     * @mbggenerated
     */
    private String deliveryNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.custom_company
     *
     * @mbggenerated
     */
    private String customCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.pit_type_name
     *
     * @mbggenerated
     */
    private String pitTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.specifications
     *
     * @mbggenerated
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.out_num
     *
     * @mbggenerated
     */
    private Integer outNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.out_time
     *
     * @mbggenerated
     */
    private String outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.reservoir
     *
     * @mbggenerated
     */
    private String reservoir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.pallet_number
     *
     * @mbggenerated
     */
    private Integer palletNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.carton_price
     *
     * @mbggenerated
     */
    private Double cartonPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.staff_id
     *
     * @mbggenerated
     */
    private String staffId;//业务员

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.deli_num
     *
     * @mbggenerated
     */
    private Integer deliNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.consignee_num
     *
     * @mbggenerated
     */
    private Integer consigneeNum;//签收数量

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.isconsignee_num
     *
     * @mbggenerated
     */
    private Integer isconsigneeNum;//未签收数量

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.isconsignee
     *
     * @mbggenerated
     */
    private String isconsignee;//未签收原因

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.scrap_num
     *
     * @mbggenerated
     */
    private Integer scrapNum;//报废

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.minority_num
     *
     * @mbggenerated
     */
    private Integer minorityNum;//少数

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.return_num
     *
     * @mbggenerated
     */
    private Integer returnNum;//退货数


    public double getAllPrice() {
        return allPrice;
    }

    public void setAllPrice(double allPrice) {
        this.allPrice = allPrice;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonOut.fake
     *
     * @mbggenerated
     */
    private double allPrice;
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.id
     *
     * @return the value of cartonOut.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.id
     *
     * @param id the value for cartonOut.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.delivery_number
     *
     * @return the value of cartonOut.delivery_number
     *
     * @mbggenerated
     */
    public String getDeliveryNumber() {
        return deliveryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.delivery_number
     *
     * @param deliveryNumber the value for cartonOut.delivery_number
     *
     * @mbggenerated
     */
    public void setDeliveryNumber(String deliveryNumber) {
        this.deliveryNumber = deliveryNumber == null ? null : deliveryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.order_account
     *
     * @return the value of cartonOut.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.order_account
     *
     * @param orderAccount the value for cartonOut.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.custom_company
     *
     * @return the value of cartonOut.custom_company
     *
     * @mbggenerated
     */
    public String getCustomCompany() {
        return customCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.custom_company
     *
     * @param customCompany the value for cartonOut.custom_company
     *
     * @mbggenerated
     */
    public void setCustomCompany(String customCompany) {
        this.customCompany = customCompany == null ? null : customCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.product_name
     *
     * @return the value of cartonOut.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.product_name
     *
     * @param productName the value for cartonOut.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.material_name
     *
     * @return the value of cartonOut.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.material_name
     *
     * @param materialName the value for cartonOut.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.pit_type_name
     *
     * @return the value of cartonOut.pit_type_name
     *
     * @mbggenerated
     */
    public String getPitTypeName() {
        return pitTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.pit_type_name
     *
     * @param pitTypeName the value for cartonOut.pit_type_name
     *
     * @mbggenerated
     */
    public void setPitTypeName(String pitTypeName) {
        this.pitTypeName = pitTypeName == null ? null : pitTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.specifications
     *
     * @return the value of cartonOut.specifications
     *
     * @mbggenerated
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.specifications
     *
     * @param specifications the value for cartonOut.specifications
     *
     * @mbggenerated
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.order_num
     *
     * @return the value of cartonOut.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.order_num
     *
     * @param orderNum the value for cartonOut.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.out_num
     *
     * @return the value of cartonOut.out_num
     *
     * @mbggenerated
     */
    public Integer getOutNum() {
        return outNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.out_num
     *
     * @param outNum the value for cartonOut.out_num
     *
     * @mbggenerated
     */
    public void setOutNum(Integer outNum) {
        this.outNum = outNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.out_time
     *
     * @return the value of cartonOut.out_time
     *
     * @mbggenerated
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.out_time
     *
     * @param outTime the value for cartonOut.out_time
     *
     * @mbggenerated
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime == null ? null : outTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.reservoir
     *
     * @return the value of cartonOut.reservoir
     *
     * @mbggenerated
     */
    public String getReservoir() {
        return reservoir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.reservoir
     *
     * @param reservoir the value for cartonOut.reservoir
     *
     * @mbggenerated
     */
    public void setReservoir(String reservoir) {
        this.reservoir = reservoir == null ? null : reservoir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.pallet_number
     *
     * @return the value of cartonOut.pallet_number
     *
     * @mbggenerated
     */
    public Integer getPalletNumber() {
        return palletNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.pallet_number
     *
     * @param palletNumber the value for cartonOut.pallet_number
     *
     * @mbggenerated
     */
    public void setPalletNumber(Integer palletNumber) {
        this.palletNumber = palletNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.carton_price
     *
     * @return the value of cartonOut.carton_price
     *
     * @mbggenerated
     */
    public Double getCartonPrice() {
        return cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.carton_price
     *
     * @param cartonPrice the value for cartonOut.carton_price
     *
     * @mbggenerated
     */
    public void setCartonPrice(Double cartonPrice) {
        this.cartonPrice = cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.staff_id
     *
     * @return the value of cartonOut.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.staff_id
     *
     * @param staffId the value for cartonOut.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.deli_num
     *
     * @return the value of cartonOut.deli_num
     *
     * @mbggenerated
     */
    public Integer getDeliNum() {
        return deliNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.deli_num
     *
     * @param deliNum the value for cartonOut.deli_num
     *
     * @mbggenerated
     */
    public void setDeliNum(Integer deliNum) {
        this.deliNum = deliNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.consignee_num
     *
     * @return the value of cartonOut.consignee_num
     *
     * @mbggenerated
     */
    public Integer getConsigneeNum() {
        return consigneeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.consignee_num
     *
     * @param consigneeNum the value for cartonOut.consignee_num
     *
     * @mbggenerated
     */
    public void setConsigneeNum(Integer consigneeNum) {
        this.consigneeNum = consigneeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.isconsignee_num
     *
     * @return the value of cartonOut.isconsignee_num
     *
     * @mbggenerated
     */
    public Integer getIsconsigneeNum() {
        return isconsigneeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.isconsignee_num
     *
     * @param isconsigneeNum the value for cartonOut.isconsignee_num
     *
     * @mbggenerated
     */
    public void setIsconsigneeNum(Integer isconsigneeNum) {
        this.isconsigneeNum = isconsigneeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.isconsignee
     *
     * @return the value of cartonOut.isconsignee
     *
     * @mbggenerated
     */
    public String getIsconsignee() {
        return isconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.isconsignee
     *
     * @param isconsignee the value for cartonOut.isconsignee
     *
     * @mbggenerated
     */
    public void setIsconsignee(String isconsignee) {
        this.isconsignee = isconsignee == null ? null : isconsignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.scrap_num
     *
     * @return the value of cartonOut.scrap_num
     *
     * @mbggenerated
     */
    public Integer getScrapNum() {
        return scrapNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.scrap_num
     *
     * @param scrapNum the value for cartonOut.scrap_num
     *
     * @mbggenerated
     */
    public void setScrapNum(Integer scrapNum) {
        this.scrapNum = scrapNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.minority_num
     *
     * @return the value of cartonOut.minority_num
     *
     * @mbggenerated
     */
    public Integer getMinorityNum() {
        return minorityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.minority_num
     *
     * @param minorityNum the value for cartonOut.minority_num
     *
     * @mbggenerated
     */
    public void setMinorityNum(Integer minorityNum) {
        this.minorityNum = minorityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.return_num
     *
     * @return the value of cartonOut.return_num
     *
     * @mbggenerated
     */
    public Integer getReturnNum() {
        return returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.return_num
     *
     * @param returnNum the value for cartonOut.return_num
     *
     * @mbggenerated
     */
    public void setReturnNum(Integer returnNum) {
        this.returnNum = returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonOut.fake
     *
     * @return the value of cartonOut.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonOut.fake
     *
     * @param fake the value for cartonOut.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}