package com.generator.pojo;

import org.springframework.web.multipart.MultipartFile;

public class CartonplantRegister {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    private Integer cartonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String cartonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private String boxSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double boxSizeHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double boxSizeWide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double boxSizeLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    private Integer boxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String pitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    private Integer materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String sizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    private Integer lineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    private Integer printedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String printedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    private Integer knifePlateNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String knifePlateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private String paperSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double paperSizeLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double paperSizeWide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double paperWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    private Integer combinationMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String workingProcedure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String printingColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String sampleBoxOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String sampleBoxTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String sampleBoxThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String cartonRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    private MultipartFile file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    private MultipartFile fileTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    private MultipartFile fileThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_id
     *
     * @return the value of cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    public Integer getCartonId() {
        return cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_id
     *
     * @param cartonId the value for cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    public void setCartonId(Integer cartonId) {
        this.cartonId = cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.custom_id
     *
     * @return the value of cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.custom_id
     *
     * @param customId the value for cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_name
     *
     * @return the value of cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    public String getCartonName() {
        return cartonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_name
     *
     * @param cartonName the value for cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    public void setCartonName(String cartonName) {
        this.cartonName = cartonName == null ? null : cartonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.box_name
     *
     * @return the value of cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    public Integer getBoxName() {
        return boxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.box_name
     *
     * @param boxName the value for cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    public void setBoxName(Integer boxName) {
        this.boxName = boxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.material_name
     *
     * @return the value of cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    public Integer getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.material_name
     *
     * @param materialName the value for cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(Integer materialName) {
        this.materialName = materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.printed_id
     *
     * @return the value of cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    public Integer getPrintedId() {
        return printedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.printed_id
     *
     * @param printedId the value for cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    public void setPrintedId(Integer printedId) {
        this.printedId = printedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.knife_plate_num
     *
     * @return the value of cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    public Integer getKnifePlateNum() {
        return knifePlateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.knife_plate_num
     *
     * @param knifePlateNum the value for cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    public void setKnifePlateNum(Integer knifePlateNum) {
        this.knifePlateNum = knifePlateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.size_type
     *
     * @return the value of cartonplant_model2.size_type
     *
     * @mbggenerated
     */
    public String getSizeType() {
        return sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.size_type
     *
     * @param sizeType the value for cartonplant_model2.size_type
     *
     * @mbggenerated
     */
    public void setSizeType(String sizeType) {
        this.sizeType = sizeType == null ? null : sizeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.line_type
     *
     * @return the value of cartonplant_model2.line_type
     *
     * @mbggenerated
     */
    public Integer getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.line_type
     *
     * @param lineType the value for cartonplant_model2.line_type
     *
     * @mbggenerated
     */
    public void setLineType(Integer lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.pit_type
     *
     * @return the value of cartonplant_model2.pit_type
     *
     * @mbggenerated
     */
    public String getPitType() {
        return pitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.pit_type
     *
     * @param pitType the value for cartonplant_model2.pit_type
     *
     * @mbggenerated
     */
    public void setPitType(String pitType) {
        this.pitType = pitType == null ? null : pitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.combination_mode
     *
     * @return the value of cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    public Integer getCombinationMode() {
        return combinationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.combination_mode
     *
     * @param combinationMode the value for cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    public void setCombinationMode(Integer combinationMode) {
        this.combinationMode = combinationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.working_procedure
     *
     * @return the value of cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    public String getWorkingProcedure() {
        return workingProcedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.working_procedure
     *
     * @param workingProcedure the value for cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    public void setWorkingProcedure(String workingProcedure) {
        this.workingProcedure = workingProcedure == null ? null : workingProcedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_remarks
     *
     * @return the value of cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    public String getCartonRemarks() {
        return cartonRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_remarks
     *
     * @param cartonRemarks the value for cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    public void setCartonRemarks(String cartonRemarks) {
        this.cartonRemarks = cartonRemarks == null ? null : cartonRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.fake
     *
     * @return the value of cartonplant_model2.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.fake
     *
     * @param fake the value for cartonplant_model2.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    public MultipartFile getFile() {
        return file;
    }

    public void setFile(MultipartFile file) {
        this.file = file;
    }

    public Double getBoxSizeHigh() {
        return boxSizeHigh;
    }

    public void setBoxSizeHigh(Double boxSizeHigh) {
        this.boxSizeHigh = boxSizeHigh;
    }

    public Double getBoxSizeWide() {
        return boxSizeWide;
    }

    public void setBoxSizeWide(Double boxSizeWide) {
        this.boxSizeWide = boxSizeWide;
    }

    public Double getBoxSizeLong() {
        return boxSizeLong;
    }

    public void setBoxSizeLong(Double boxSizeLong) {
        this.boxSizeLong = boxSizeLong;
    }

    public Double getLine() {
        return line;
    }

    public void setLine(Double line) {
        this.line = line;
    }

    public String getPrintedName() {
        return printedName;
    }

    public void setPrintedName(String printedName) {
        this.printedName = printedName;
    }

    public String getKnifePlateName() {
        return knifePlateName;
    }

    public void setKnifePlateName(String knifePlateName) {
        this.knifePlateName = knifePlateName;
    }

    public Double getPaperWeight() {
        return paperWeight;
    }

    public void setPaperWeight(Double paperWeight) {
        this.paperWeight = paperWeight;
    }

    public String getPrintingColor() {
        return printingColor;
    }

    public void setPrintingColor(String printingColor) {
        this.printingColor = printingColor;
    }

    public String getSampleBoxOne() {
        return sampleBoxOne;
    }

    public void setSampleBoxOne(String sampleBoxOne) {
        this.sampleBoxOne = sampleBoxOne;
    }

    public String getSampleBoxTwo() {
        return sampleBoxTwo;
    }

    public void setSampleBoxTwo(String sampleBoxTwo) {
        this.sampleBoxTwo = sampleBoxTwo;
    }

    public String getSampleBoxThree() {
        return sampleBoxThree;
    }

    public void setSampleBoxThree(String sampleBoxThree) {
        this.sampleBoxThree = sampleBoxThree;
    }

    public MultipartFile getFileTwo() {
        return fileTwo;
    }

    public void setFileTwo(MultipartFile fileTwo) {
        this.fileTwo = fileTwo;
    }

    public MultipartFile getFileThree() {
        return fileThree;
    }

    public void setFileThree(MultipartFile fileThree) {
        this.fileThree = fileThree;
    }

    public Double getPaperSizeLong() {
        return paperSizeLong;
    }

    public void setPaperSizeLong(Double paperSizeLong) {
        this.paperSizeLong = paperSizeLong;
    }

    public Double getPaperSizeWide() {
        return paperSizeWide;
    }

    public void setPaperSizeWide(Double paperSizeWide) {
        this.paperSizeWide = paperSizeWide;
    }

    public String getPaperSize() {
        return paperSize;
    }

    public void setPaperSize(String paperSize) {
        this.paperSize = paperSize;
    }

    public String getBoxSize() {
        return boxSize;
    }

    public void setBoxSize(String boxSize) {
        this.boxSize = boxSize;
    }
}