package com.generator.pojo;

import java.util.List;

public class Cartonwarehousing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.rk_id
     *
     * @mbggenerated
     */
    private Integer rkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.carton_length
     *
     * @mbggenerated
     */
    private Double cartonLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.carton_width
     *
     * @mbggenerated
     */
    private Double cartonWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.carton_height
     *
     * @mbggenerated
     */
    private Double cartonHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.pit_type_name
     *
     * @mbggenerated
     */
    private String pitTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.carton_price
     *
     * @mbggenerated
     */
    private Double cartonPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.rk_num
     *
     * @mbggenerated
     */
    private Integer rkNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.rk_time
     *
     * @mbggenerated
     */
    private String rkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.reservoir
     *
     * @mbggenerated
     */
    private String reservoir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.pallet_number
     *
     * @mbggenerated
     */
    private Integer palletNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.rk_name
     *
     * @mbggenerated
     */
    private String rkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.rk_pihao
     *
     * @mbggenerated
     */
    private String rkPihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.baosun
     *
     * @mbggenerated
     */
    private Integer baosun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonWarehousing.number
     *
     * @mbggenerated
     */
    private Integer number;

    private List<Cartonwarehousing> list;

    public List<Cartonwarehousing> getList() {
        return list;
    }

    public void setList(List<Cartonwarehousing> list) {
        this.list = list;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.rk_id
     *
     * @return the value of cartonWarehousing.rk_id
     *
     * @mbggenerated
     */
    public Integer getRkId() {
        return rkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.rk_id
     *
     * @param rkId the value for cartonWarehousing.rk_id
     *
     * @mbggenerated
     */
    public void setRkId(Integer rkId) {
        this.rkId = rkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.order_account
     *
     * @return the value of cartonWarehousing.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.order_account
     *
     * @param orderAccount the value for cartonWarehousing.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.custom_name
     *
     * @return the value of cartonWarehousing.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.custom_name
     *
     * @param customName the value for cartonWarehousing.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.staff_id
     *
     * @return the value of cartonWarehousing.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.staff_id
     *
     * @param staffId the value for cartonWarehousing.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.product_name
     *
     * @return the value of cartonWarehousing.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.product_name
     *
     * @param productName the value for cartonWarehousing.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.material_name
     *
     * @return the value of cartonWarehousing.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.material_name
     *
     * @param materialName the value for cartonWarehousing.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.carton_length
     *
     * @return the value of cartonWarehousing.carton_length
     *
     * @mbggenerated
     */
    public Double getCartonLength() {
        return cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.carton_length
     *
     * @param cartonLength the value for cartonWarehousing.carton_length
     *
     * @mbggenerated
     */
    public void setCartonLength(Double cartonLength) {
        this.cartonLength = cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.carton_width
     *
     * @return the value of cartonWarehousing.carton_width
     *
     * @mbggenerated
     */
    public Double getCartonWidth() {
        return cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.carton_width
     *
     * @param cartonWidth the value for cartonWarehousing.carton_width
     *
     * @mbggenerated
     */
    public void setCartonWidth(Double cartonWidth) {
        this.cartonWidth = cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.carton_height
     *
     * @return the value of cartonWarehousing.carton_height
     *
     * @mbggenerated
     */
    public Double getCartonHeight() {
        return cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.carton_height
     *
     * @param cartonHeight the value for cartonWarehousing.carton_height
     *
     * @mbggenerated
     */
    public void setCartonHeight(Double cartonHeight) {
        this.cartonHeight = cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.pit_type_name
     *
     * @return the value of cartonWarehousing.pit_type_name
     *
     * @mbggenerated
     */
    public String getPitTypeName() {
        return pitTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.pit_type_name
     *
     * @param pitTypeName the value for cartonWarehousing.pit_type_name
     *
     * @mbggenerated
     */
    public void setPitTypeName(String pitTypeName) {
        this.pitTypeName = pitTypeName == null ? null : pitTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.carton_price
     *
     * @return the value of cartonWarehousing.carton_price
     *
     * @mbggenerated
     */
    public Double getCartonPrice() {
        return cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.carton_price
     *
     * @param cartonPrice the value for cartonWarehousing.carton_price
     *
     * @mbggenerated
     */
    public void setCartonPrice(Double cartonPrice) {
        this.cartonPrice = cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.order_num
     *
     * @return the value of cartonWarehousing.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.order_num
     *
     * @param orderNum the value for cartonWarehousing.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.rk_num
     *
     * @return the value of cartonWarehousing.rk_num
     *
     * @mbggenerated
     */
    public Integer getRkNum() {
        return rkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.rk_num
     *
     * @param rkNum the value for cartonWarehousing.rk_num
     *
     * @mbggenerated
     */
    public void setRkNum(Integer rkNum) {
        this.rkNum = rkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.rk_time
     *
     * @return the value of cartonWarehousing.rk_time
     *
     * @mbggenerated
     */
    public String getRkTime() {
        return rkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.rk_time
     *
     * @param rkTime the value for cartonWarehousing.rk_time
     *
     * @mbggenerated
     */
    public void setRkTime(String rkTime) {
        this.rkTime = rkTime == null ? null : rkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.reservoir
     *
     * @return the value of cartonWarehousing.reservoir
     *
     * @mbggenerated
     */
    public String getReservoir() {
        return reservoir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.reservoir
     *
     * @param reservoir the value for cartonWarehousing.reservoir
     *
     * @mbggenerated
     */
    public void setReservoir(String reservoir) {
        this.reservoir = reservoir == null ? null : reservoir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.pallet_number
     *
     * @return the value of cartonWarehousing.pallet_number
     *
     * @mbggenerated
     */
    public Integer getPalletNumber() {
        return palletNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.pallet_number
     *
     * @param palletNumber the value for cartonWarehousing.pallet_number
     *
     * @mbggenerated
     */
    public void setPalletNumber(Integer palletNumber) {
        this.palletNumber = palletNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.fake
     *
     * @return the value of cartonWarehousing.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.fake
     *
     * @param fake the value for cartonWarehousing.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.rk_name
     *
     * @return the value of cartonWarehousing.rk_name
     *
     * @mbggenerated
     */
    public String getRkName() {
        return rkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.rk_name
     *
     * @param rkName the value for cartonWarehousing.rk_name
     *
     * @mbggenerated
     */
    public void setRkName(String rkName) {
        this.rkName = rkName == null ? null : rkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.rk_pihao
     *
     * @return the value of cartonWarehousing.rk_pihao
     *
     * @mbggenerated
     */
    public String getRkPihao() {
        return rkPihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.rk_pihao
     *
     * @param rkPihao the value for cartonWarehousing.rk_pihao
     *
     * @mbggenerated
     */
    public void setRkPihao(String rkPihao) {
        this.rkPihao = rkPihao == null ? null : rkPihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.baosun
     *
     * @return the value of cartonWarehousing.baosun
     *
     * @mbggenerated
     */
    public Integer getBaosun() {
        return baosun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.baosun
     *
     * @param baosun the value for cartonWarehousing.baosun
     *
     * @mbggenerated
     */
    public void setBaosun(Integer baosun) {
        this.baosun = baosun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonWarehousing.number
     *
     * @return the value of cartonWarehousing.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonWarehousing.number
     *
     * @param number the value for cartonWarehousing.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}