package com.generator.pojo;

import org.springframework.web.multipart.MultipartFile;

public class CartonplantModel2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    private Integer cartonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    private String cartonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.box_id
     *
     * @mbggenerated
     */
    private Integer boxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    private String boxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.pit_id
     *
     * @mbggenerated
     */
    private Integer pitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.pit_type
     *
     * @mbggenerated
     */
    private String pitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    private Double cartonLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_width
     *
     * @mbggenerated
     */
    private Double cartonWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_height
     *
     * @mbggenerated
     */
    private Double cartonHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.card_length
     *
     * @mbggenerated
     */
    private Double cardLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.card_width
     *
     * @mbggenerated
     */
    private Double cardWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.size_type
     *
     * @mbggenerated
     */
    private String sizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.length_line
     *
     * @mbggenerated
     */
    private String lengthLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.width_line
     *
     * @mbggenerated
     */
    private String widthLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.line_type
     *
     * @mbggenerated
     */
    private Integer lineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.blanking_height
     *
     * @mbggenerated
     */
    private Double blankingHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.blanking_width
     *
     * @mbggenerated
     */
    private Double blankingWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_price
     *
     * @mbggenerated
     */
    private Double cartonPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    private String workingProcedure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.color_num
     *
     * @mbggenerated
     */
    private String colorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    private String printedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.printed_name
     *
     * @mbggenerated
     */
    private String printedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.print_picture
     *
     * @mbggenerated
     */
    private String printPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    private String knifePlateNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.knife_plate_name
     *
     * @mbggenerated
     */
    private String knifePlateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.knife_picture
     *
     * @mbggenerated
     */
    private String knifePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    private Integer combinationMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.nailing_num
     *
     * @mbggenerated
     */
    private Integer nailingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.pack_num
     *
     * @mbggenerated
     */
    private Integer packNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.fabric_bei
     *
     * @mbggenerated
     */
    private Integer fabricBei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.fabric_width
     *
     * @mbggenerated
     */
    private Double fabricWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_unit
     *
     * @mbggenerated
     */
    private String cartonUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    private String cartonRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_time
     *
     * @mbggenerated
     */
    private String cartonTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.open_number
     *
     * @mbggenerated
     */
    private String openNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_image
     *
     * @mbggenerated
     */
    private String cartonImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_spec
     *
     * @mbggenerated
     */
    private String cartonSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cartonplant_model2.carton_number
     *
     * @mbggenerated
     */
    private String cartonNumber;

    private MultipartFile file;

    public MultipartFile getFile() {
        return file;
    }

    public void setFile(MultipartFile file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_id
     *
     * @return the value of cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    public Integer getCartonId() {
        return cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_id
     *
     * @param cartonId the value for cartonplant_model2.carton_id
     *
     * @mbggenerated
     */
    public void setCartonId(Integer cartonId) {
        this.cartonId = cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.custom_id
     *
     * @return the value of cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.custom_id
     *
     * @param customId the value for cartonplant_model2.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.custom_name
     *
     * @return the value of cartonplant_model2.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.custom_name
     *
     * @param customName the value for cartonplant_model2.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_name
     *
     * @return the value of cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    public String getCartonName() {
        return cartonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_name
     *
     * @param cartonName the value for cartonplant_model2.carton_name
     *
     * @mbggenerated
     */
    public void setCartonName(String cartonName) {
        this.cartonName = cartonName == null ? null : cartonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.box_id
     *
     * @return the value of cartonplant_model2.box_id
     *
     * @mbggenerated
     */
    public Integer getBoxId() {
        return boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.box_id
     *
     * @param boxId the value for cartonplant_model2.box_id
     *
     * @mbggenerated
     */
    public void setBoxId(Integer boxId) {
        this.boxId = boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.box_name
     *
     * @return the value of cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    public String getBoxName() {
        return boxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.box_name
     *
     * @param boxName the value for cartonplant_model2.box_name
     *
     * @mbggenerated
     */
    public void setBoxName(String boxName) {
        this.boxName = boxName == null ? null : boxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.material_name
     *
     * @return the value of cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.material_name
     *
     * @param materialName the value for cartonplant_model2.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.pit_id
     *
     * @return the value of cartonplant_model2.pit_id
     *
     * @mbggenerated
     */
    public Integer getPitId() {
        return pitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.pit_id
     *
     * @param pitId the value for cartonplant_model2.pit_id
     *
     * @mbggenerated
     */
    public void setPitId(Integer pitId) {
        this.pitId = pitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.pit_type
     *
     * @return the value of cartonplant_model2.pit_type
     *
     * @mbggenerated
     */
    public String getPitType() {
        return pitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.pit_type
     *
     * @param pitType the value for cartonplant_model2.pit_type
     *
     * @mbggenerated
     */
    public void setPitType(String pitType) {
        this.pitType = pitType == null ? null : pitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_length
     *
     * @return the value of cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    public Double getCartonLength() {
        return cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_length
     *
     * @param cartonLength the value for cartonplant_model2.carton_length
     *
     * @mbggenerated
     */
    public void setCartonLength(Double cartonLength) {
        this.cartonLength = cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_width
     *
     * @return the value of cartonplant_model2.carton_width
     *
     * @mbggenerated
     */
    public Double getCartonWidth() {
        return cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_width
     *
     * @param cartonWidth the value for cartonplant_model2.carton_width
     *
     * @mbggenerated
     */
    public void setCartonWidth(Double cartonWidth) {
        this.cartonWidth = cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_height
     *
     * @return the value of cartonplant_model2.carton_height
     *
     * @mbggenerated
     */
    public Double getCartonHeight() {
        return cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_height
     *
     * @param cartonHeight the value for cartonplant_model2.carton_height
     *
     * @mbggenerated
     */
    public void setCartonHeight(Double cartonHeight) {
        this.cartonHeight = cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.card_length
     *
     * @return the value of cartonplant_model2.card_length
     *
     * @mbggenerated
     */
    public Double getCardLength() {
        return cardLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.card_length
     *
     * @param cardLength the value for cartonplant_model2.card_length
     *
     * @mbggenerated
     */
    public void setCardLength(Double cardLength) {
        this.cardLength = cardLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.card_width
     *
     * @return the value of cartonplant_model2.card_width
     *
     * @mbggenerated
     */
    public Double getCardWidth() {
        return cardWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.card_width
     *
     * @param cardWidth the value for cartonplant_model2.card_width
     *
     * @mbggenerated
     */
    public void setCardWidth(Double cardWidth) {
        this.cardWidth = cardWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.size_type
     *
     * @return the value of cartonplant_model2.size_type
     *
     * @mbggenerated
     */
    public String getSizeType() {
        return sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.size_type
     *
     * @param sizeType the value for cartonplant_model2.size_type
     *
     * @mbggenerated
     */
    public void setSizeType(String sizeType) {
        this.sizeType = sizeType == null ? null : sizeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.length_line
     *
     * @return the value of cartonplant_model2.length_line
     *
     * @mbggenerated
     */
    public String getLengthLine() {
        return lengthLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.length_line
     *
     * @param lengthLine the value for cartonplant_model2.length_line
     *
     * @mbggenerated
     */
    public void setLengthLine(String lengthLine) {
        this.lengthLine = lengthLine == null ? null : lengthLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.width_line
     *
     * @return the value of cartonplant_model2.width_line
     *
     * @mbggenerated
     */
    public String getWidthLine() {
        return widthLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.width_line
     *
     * @param widthLine the value for cartonplant_model2.width_line
     *
     * @mbggenerated
     */
    public void setWidthLine(String widthLine) {
        this.widthLine = widthLine == null ? null : widthLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.line_type
     *
     * @return the value of cartonplant_model2.line_type
     *
     * @mbggenerated
     */
    public Integer getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.line_type
     *
     * @param lineType the value for cartonplant_model2.line_type
     *
     * @mbggenerated
     */
    public void setLineType(Integer lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.blanking_height
     *
     * @return the value of cartonplant_model2.blanking_height
     *
     * @mbggenerated
     */
    public Double getBlankingHeight() {
        return blankingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.blanking_height
     *
     * @param blankingHeight the value for cartonplant_model2.blanking_height
     *
     * @mbggenerated
     */
    public void setBlankingHeight(Double blankingHeight) {
        this.blankingHeight = blankingHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.blanking_width
     *
     * @return the value of cartonplant_model2.blanking_width
     *
     * @mbggenerated
     */
    public Double getBlankingWidth() {
        return blankingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.blanking_width
     *
     * @param blankingWidth the value for cartonplant_model2.blanking_width
     *
     * @mbggenerated
     */
    public void setBlankingWidth(Double blankingWidth) {
        this.blankingWidth = blankingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_price
     *
     * @return the value of cartonplant_model2.carton_price
     *
     * @mbggenerated
     */
    public Double getCartonPrice() {
        return cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_price
     *
     * @param cartonPrice the value for cartonplant_model2.carton_price
     *
     * @mbggenerated
     */
    public void setCartonPrice(Double cartonPrice) {
        this.cartonPrice = cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.working_procedure
     *
     * @return the value of cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    public String getWorkingProcedure() {
        return workingProcedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.working_procedure
     *
     * @param workingProcedure the value for cartonplant_model2.working_procedure
     *
     * @mbggenerated
     */
    public void setWorkingProcedure(String workingProcedure) {
        this.workingProcedure = workingProcedure == null ? null : workingProcedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.color_num
     *
     * @return the value of cartonplant_model2.color_num
     *
     * @mbggenerated
     */
    public String getColorNum() {
        return colorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.color_num
     *
     * @param colorNum the value for cartonplant_model2.color_num
     *
     * @mbggenerated
     */
    public void setColorNum(String colorNum) {
        this.colorNum = colorNum == null ? null : colorNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.printed_id
     *
     * @return the value of cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    public String getPrintedId() {
        return printedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.printed_id
     *
     * @param printedId the value for cartonplant_model2.printed_id
     *
     * @mbggenerated
     */
    public void setPrintedId(String printedId) {
        this.printedId = printedId == null ? null : printedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.printed_name
     *
     * @return the value of cartonplant_model2.printed_name
     *
     * @mbggenerated
     */
    public String getPrintedName() {
        return printedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.printed_name
     *
     * @param printedName the value for cartonplant_model2.printed_name
     *
     * @mbggenerated
     */
    public void setPrintedName(String printedName) {
        this.printedName = printedName == null ? null : printedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.print_picture
     *
     * @return the value of cartonplant_model2.print_picture
     *
     * @mbggenerated
     */
    public String getPrintPicture() {
        return printPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.print_picture
     *
     * @param printPicture the value for cartonplant_model2.print_picture
     *
     * @mbggenerated
     */
    public void setPrintPicture(String printPicture) {
        this.printPicture = printPicture == null ? null : printPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.knife_plate_num
     *
     * @return the value of cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    public String getKnifePlateNum() {
        return knifePlateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.knife_plate_num
     *
     * @param knifePlateNum the value for cartonplant_model2.knife_plate_num
     *
     * @mbggenerated
     */
    public void setKnifePlateNum(String knifePlateNum) {
        this.knifePlateNum = knifePlateNum == null ? null : knifePlateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.knife_plate_name
     *
     * @return the value of cartonplant_model2.knife_plate_name
     *
     * @mbggenerated
     */
    public String getKnifePlateName() {
        return knifePlateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.knife_plate_name
     *
     * @param knifePlateName the value for cartonplant_model2.knife_plate_name
     *
     * @mbggenerated
     */
    public void setKnifePlateName(String knifePlateName) {
        this.knifePlateName = knifePlateName == null ? null : knifePlateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.knife_picture
     *
     * @return the value of cartonplant_model2.knife_picture
     *
     * @mbggenerated
     */
    public String getKnifePicture() {
        return knifePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.knife_picture
     *
     * @param knifePicture the value for cartonplant_model2.knife_picture
     *
     * @mbggenerated
     */
    public void setKnifePicture(String knifePicture) {
        this.knifePicture = knifePicture == null ? null : knifePicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.combination_mode
     *
     * @return the value of cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    public Integer getCombinationMode() {
        return combinationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.combination_mode
     *
     * @param combinationMode the value for cartonplant_model2.combination_mode
     *
     * @mbggenerated
     */
    public void setCombinationMode(Integer combinationMode) {
        this.combinationMode = combinationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.nailing_num
     *
     * @return the value of cartonplant_model2.nailing_num
     *
     * @mbggenerated
     */
    public Integer getNailingNum() {
        return nailingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.nailing_num
     *
     * @param nailingNum the value for cartonplant_model2.nailing_num
     *
     * @mbggenerated
     */
    public void setNailingNum(Integer nailingNum) {
        this.nailingNum = nailingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.pack_num
     *
     * @return the value of cartonplant_model2.pack_num
     *
     * @mbggenerated
     */
    public Integer getPackNum() {
        return packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.pack_num
     *
     * @param packNum the value for cartonplant_model2.pack_num
     *
     * @mbggenerated
     */
    public void setPackNum(Integer packNum) {
        this.packNum = packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.fabric_bei
     *
     * @return the value of cartonplant_model2.fabric_bei
     *
     * @mbggenerated
     */
    public Integer getFabricBei() {
        return fabricBei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.fabric_bei
     *
     * @param fabricBei the value for cartonplant_model2.fabric_bei
     *
     * @mbggenerated
     */
    public void setFabricBei(Integer fabricBei) {
        this.fabricBei = fabricBei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.fabric_width
     *
     * @return the value of cartonplant_model2.fabric_width
     *
     * @mbggenerated
     */
    public Double getFabricWidth() {
        return fabricWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.fabric_width
     *
     * @param fabricWidth the value for cartonplant_model2.fabric_width
     *
     * @mbggenerated
     */
    public void setFabricWidth(Double fabricWidth) {
        this.fabricWidth = fabricWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_unit
     *
     * @return the value of cartonplant_model2.carton_unit
     *
     * @mbggenerated
     */
    public String getCartonUnit() {
        return cartonUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_unit
     *
     * @param cartonUnit the value for cartonplant_model2.carton_unit
     *
     * @mbggenerated
     */
    public void setCartonUnit(String cartonUnit) {
        this.cartonUnit = cartonUnit == null ? null : cartonUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_remarks
     *
     * @return the value of cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    public String getCartonRemarks() {
        return cartonRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_remarks
     *
     * @param cartonRemarks the value for cartonplant_model2.carton_remarks
     *
     * @mbggenerated
     */
    public void setCartonRemarks(String cartonRemarks) {
        this.cartonRemarks = cartonRemarks == null ? null : cartonRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_time
     *
     * @return the value of cartonplant_model2.carton_time
     *
     * @mbggenerated
     */
    public String getCartonTime() {
        return cartonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_time
     *
     * @param cartonTime the value for cartonplant_model2.carton_time
     *
     * @mbggenerated
     */
    public void setCartonTime(String cartonTime) {
        this.cartonTime = cartonTime == null ? null : cartonTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.fake
     *
     * @return the value of cartonplant_model2.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.fake
     *
     * @param fake the value for cartonplant_model2.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.open_number
     *
     * @return the value of cartonplant_model2.open_number
     *
     * @mbggenerated
     */
    public String getOpenNumber() {
        return openNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.open_number
     *
     * @param openNumber the value for cartonplant_model2.open_number
     *
     * @mbggenerated
     */
    public void setOpenNumber(String openNumber) {
        this.openNumber = openNumber == null ? null : openNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_image
     *
     * @return the value of cartonplant_model2.carton_image
     *
     * @mbggenerated
     */
    public String getCartonImage() {
        return cartonImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_image
     *
     * @param cartonImage the value for cartonplant_model2.carton_image
     *
     * @mbggenerated
     */
    public void setCartonImage(String cartonImage) {
        this.cartonImage = cartonImage == null ? null : cartonImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_spec
     *
     * @return the value of cartonplant_model2.carton_spec
     *
     * @mbggenerated
     */
    public String getCartonSpec() {
        return cartonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_spec
     *
     * @param cartonSpec the value for cartonplant_model2.carton_spec
     *
     * @mbggenerated
     */
    public void setCartonSpec(String cartonSpec) {
        this.cartonSpec = cartonSpec == null ? null : cartonSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cartonplant_model2.carton_number
     *
     * @return the value of cartonplant_model2.carton_number
     *
     * @mbggenerated
     */
    public String getCartonNumber() {
        return cartonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cartonplant_model2.carton_number
     *
     * @param cartonNumber the value for cartonplant_model2.carton_number
     *
     * @mbggenerated
     */
    public void setCartonNumber(String cartonNumber) {
        this.cartonNumber = cartonNumber == null ? null : cartonNumber.trim();
    }
}