package com.generator.pojo;

public class Custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_tel
     *
     * @mbggenerated
     */
    private String customTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_address
     *
     * @mbggenerated
     */
    private String customAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_qq
     *
     * @mbggenerated
     */
    private String customQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.wechat
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_quota
     *
     * @mbggenerated
     */
    private Double customQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.credit_day
     *
     * @mbggenerated
     */
    private Integer creditDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_type
     *
     * @mbggenerated
     */
    private Integer customType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.zday
     *
     * @mbggenerated
     */
    private Integer zday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_sale
     *
     * @mbggenerated
     */
    private Double customSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.is_shui
     *
     * @mbggenerated
     */
    private Integer isShui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.delivery_distance
     *
     * @mbggenerated
     */
    private Double deliveryDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.delivery_style
     *
     * @mbggenerated
     */
    private String deliveryStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_compary
     *
     * @mbggenerated
     */
    private String customCompary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.fax
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.opening_bank
     *
     * @mbggenerated
     */
    private String openingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.account_number
     *
     * @mbggenerated
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.reservoir_area
     *
     * @mbggenerated
     */
    private String reservoirArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.recognition_number
     *
     * @mbggenerated
     */
    private String recognitionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.duty_paragraph
     *
     * @mbggenerated
     */
    private String dutyParagraph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.payment_method
     *
     * @mbggenerated
     */
    private String paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.customer_balance
     *
     * @mbggenerated
     */
    private Double customerBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.registration_time
     *
     * @mbggenerated
     */
    private String registrationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_id
     *
     * @return the value of custom.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_id
     *
     * @param customId the value for custom.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_name
     *
     * @return the value of custom.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_name
     *
     * @param customName the value for custom.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.staff_id
     *
     * @return the value of custom.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.staff_id
     *
     * @param staffId the value for custom.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_tel
     *
     * @return the value of custom.custom_tel
     *
     * @mbggenerated
     */
    public String getCustomTel() {
        return customTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_tel
     *
     * @param customTel the value for custom.custom_tel
     *
     * @mbggenerated
     */
    public void setCustomTel(String customTel) {
        this.customTel = customTel == null ? null : customTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_address
     *
     * @return the value of custom.custom_address
     *
     * @mbggenerated
     */
    public String getCustomAddress() {
        return customAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_address
     *
     * @param customAddress the value for custom.custom_address
     *
     * @mbggenerated
     */
    public void setCustomAddress(String customAddress) {
        this.customAddress = customAddress == null ? null : customAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_qq
     *
     * @return the value of custom.custom_qq
     *
     * @mbggenerated
     */
    public String getCustomQq() {
        return customQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_qq
     *
     * @param customQq the value for custom.custom_qq
     *
     * @mbggenerated
     */
    public void setCustomQq(String customQq) {
        this.customQq = customQq == null ? null : customQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.wechat
     *
     * @return the value of custom.wechat
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.wechat
     *
     * @param wechat the value for custom.wechat
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_quota
     *
     * @return the value of custom.custom_quota
     *
     * @mbggenerated
     */
    public Double getCustomQuota() {
        return customQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_quota
     *
     * @param customQuota the value for custom.custom_quota
     *
     * @mbggenerated
     */
    public void setCustomQuota(Double customQuota) {
        this.customQuota = customQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.credit_day
     *
     * @return the value of custom.credit_day
     *
     * @mbggenerated
     */
    public Integer getCreditDay() {
        return creditDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.credit_day
     *
     * @param creditDay the value for custom.credit_day
     *
     * @mbggenerated
     */
    public void setCreditDay(Integer creditDay) {
        this.creditDay = creditDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_type
     *
     * @return the value of custom.custom_type
     *
     * @mbggenerated
     */
    public Integer getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_type
     *
     * @param customType the value for custom.custom_type
     *
     * @mbggenerated
     */
    public void setCustomType(Integer customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.zday
     *
     * @return the value of custom.zday
     *
     * @mbggenerated
     */
    public Integer getZday() {
        return zday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.zday
     *
     * @param zday the value for custom.zday
     *
     * @mbggenerated
     */
    public void setZday(Integer zday) {
        this.zday = zday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_sale
     *
     * @return the value of custom.custom_sale
     *
     * @mbggenerated
     */
    public Double getCustomSale() {
        return customSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_sale
     *
     * @param customSale the value for custom.custom_sale
     *
     * @mbggenerated
     */
    public void setCustomSale(Double customSale) {
        this.customSale = customSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.is_shui
     *
     * @return the value of custom.is_shui
     *
     * @mbggenerated
     */
    public Integer getIsShui() {
        return isShui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.is_shui
     *
     * @param isShui the value for custom.is_shui
     *
     * @mbggenerated
     */
    public void setIsShui(Integer isShui) {
        this.isShui = isShui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.delivery_distance
     *
     * @return the value of custom.delivery_distance
     *
     * @mbggenerated
     */
    public Double getDeliveryDistance() {
        return deliveryDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.delivery_distance
     *
     * @param deliveryDistance the value for custom.delivery_distance
     *
     * @mbggenerated
     */
    public void setDeliveryDistance(Double deliveryDistance) {
        this.deliveryDistance = deliveryDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.delivery_style
     *
     * @return the value of custom.delivery_style
     *
     * @mbggenerated
     */
    public String getDeliveryStyle() {
        return deliveryStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.delivery_style
     *
     * @param deliveryStyle the value for custom.delivery_style
     *
     * @mbggenerated
     */
    public void setDeliveryStyle(String deliveryStyle) {
        this.deliveryStyle = deliveryStyle == null ? null : deliveryStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_compary
     *
     * @return the value of custom.custom_compary
     *
     * @mbggenerated
     */
    public String getCustomCompary() {
        return customCompary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_compary
     *
     * @param customCompary the value for custom.custom_compary
     *
     * @mbggenerated
     */
    public void setCustomCompary(String customCompary) {
        this.customCompary = customCompary == null ? null : customCompary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.fax
     *
     * @return the value of custom.fax
     *
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.fax
     *
     * @param fax the value for custom.fax
     *
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.opening_bank
     *
     * @return the value of custom.opening_bank
     *
     * @mbggenerated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.opening_bank
     *
     * @param openingBank the value for custom.opening_bank
     *
     * @mbggenerated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.industry
     *
     * @return the value of custom.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.industry
     *
     * @param industry the value for custom.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.account_number
     *
     * @return the value of custom.account_number
     *
     * @mbggenerated
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.account_number
     *
     * @param accountNumber the value for custom.account_number
     *
     * @mbggenerated
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.reservoir_area
     *
     * @return the value of custom.reservoir_area
     *
     * @mbggenerated
     */
    public String getReservoirArea() {
        return reservoirArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.reservoir_area
     *
     * @param reservoirArea the value for custom.reservoir_area
     *
     * @mbggenerated
     */
    public void setReservoirArea(String reservoirArea) {
        this.reservoirArea = reservoirArea == null ? null : reservoirArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.recognition_number
     *
     * @return the value of custom.recognition_number
     *
     * @mbggenerated
     */
    public String getRecognitionNumber() {
        return recognitionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.recognition_number
     *
     * @param recognitionNumber the value for custom.recognition_number
     *
     * @mbggenerated
     */
    public void setRecognitionNumber(String recognitionNumber) {
        this.recognitionNumber = recognitionNumber == null ? null : recognitionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.duty_paragraph
     *
     * @return the value of custom.duty_paragraph
     *
     * @mbggenerated
     */
    public String getDutyParagraph() {
        return dutyParagraph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.duty_paragraph
     *
     * @param dutyParagraph the value for custom.duty_paragraph
     *
     * @mbggenerated
     */
    public void setDutyParagraph(String dutyParagraph) {
        this.dutyParagraph = dutyParagraph == null ? null : dutyParagraph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.payment_method
     *
     * @return the value of custom.payment_method
     *
     * @mbggenerated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.payment_method
     *
     * @param paymentMethod the value for custom.payment_method
     *
     * @mbggenerated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.customer_balance
     *
     * @return the value of custom.customer_balance
     *
     * @mbggenerated
     */
    public Double getCustomerBalance() {
        return customerBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.customer_balance
     *
     * @param customerBalance the value for custom.customer_balance
     *
     * @mbggenerated
     */
    public void setCustomerBalance(Double customerBalance) {
        this.customerBalance = customerBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.fake
     *
     * @return the value of custom.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.fake
     *
     * @param fake the value for custom.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.remarks
     *
     * @return the value of custom.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.remarks
     *
     * @param remarks the value for custom.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.registration_time
     *
     * @return the value of custom.registration_time
     *
     * @mbggenerated
     */
    public String getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.registration_time
     *
     * @param registrationTime the value for custom.registration_time
     *
     * @mbggenerated
     */
    public void setRegistrationTime(String registrationTime) {
        this.registrationTime = registrationTime == null ? null : registrationTime.trim();
    }
}