package com.generator.pojo;

public class Flut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flut.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flut.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flut.coefficient
     *
     * @mbggenerated
     */
    private Double coefficient;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flut.id
     *
     * @return the value of flut.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flut.id
     *
     * @param id the value for flut.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flut.name
     *
     * @return the value of flut.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flut.name
     *
     * @param name the value for flut.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flut.coefficient
     *
     * @return the value of flut.coefficient
     *
     * @mbggenerated
     */
    public Double getCoefficient() {
        return coefficient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flut.coefficient
     *
     * @param coefficient the value for flut.coefficient
     *
     * @mbggenerated
     */
    public void setCoefficient(Double coefficient) {
        this.coefficient = coefficient;
    }
}