package com.generator.pojo;

import org.springframework.web.multipart.MultipartFile;

public class KnifeTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_template_id
     *
     * @mbggenerated
     */
    private Integer knifeTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_plate_num
     *
     * @mbggenerated
     */
    private String knifePlateNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_template_name
     *
     * @mbggenerated
     */
    private String knifeTemplateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_size
     *
     * @mbggenerated
     */
    private Integer knifeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_file
     *
     * @mbggenerated
     */
    private String knifeFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_code
     *
     * @mbggenerated
     */
    private String knifeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_picture
     *
     * @mbggenerated
     */
    private String knifePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knife_template.knife_picture
     *
     * @mbggenerated
     */
    private MultipartFile knifePictureFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_template_id
     *
     * @return the value of knife_template.knife_template_id
     *
     * @mbggenerated
     */
    public Integer getKnifeTemplateId() {
        return knifeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_template_id
     *
     * @param knifeTemplateId the value for knife_template.knife_template_id
     *
     * @mbggenerated
     */
    public void setKnifeTemplateId(Integer knifeTemplateId) {
        this.knifeTemplateId = knifeTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_plate_num
     *
     * @return the value of knife_template.knife_plate_num
     *
     * @mbggenerated
     */
    public String getKnifePlateNum() {
        return knifePlateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_plate_num
     *
     * @param knifePlateNum the value for knife_template.knife_plate_num
     *
     * @mbggenerated
     */
    public void setKnifePlateNum(String knifePlateNum) {
        this.knifePlateNum = knifePlateNum == null ? null : knifePlateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_template_name
     *
     * @return the value of knife_template.knife_template_name
     *
     * @mbggenerated
     */
    public String getKnifeTemplateName() {
        return knifeTemplateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_template_name
     *
     * @param knifeTemplateName the value for knife_template.knife_template_name
     *
     * @mbggenerated
     */
    public void setKnifeTemplateName(String knifeTemplateName) {
        this.knifeTemplateName = knifeTemplateName == null ? null : knifeTemplateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_size
     *
     * @return the value of knife_template.knife_size
     *
     * @mbggenerated
     */
    public Integer getKnifeSize() {
        return knifeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_size
     *
     * @param knifeSize the value for knife_template.knife_size
     *
     * @mbggenerated
     */
    public void setKnifeSize(Integer knifeSize) {
        this.knifeSize = knifeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_file
     *
     * @return the value of knife_template.knife_file
     *
     * @mbggenerated
     */
    public String getKnifeFile() {
        return knifeFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_file
     *
     * @param knifeFile the value for knife_template.knife_file
     *
     * @mbggenerated
     */
    public void setKnifeFile(String knifeFile) {
        this.knifeFile = knifeFile == null ? null : knifeFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.fake
     *
     * @return the value of knife_template.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.fake
     *
     * @param fake the value for knife_template.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_code
     *
     * @return the value of knife_template.knife_code
     *
     * @mbggenerated
     */
    public String getKnifeCode() {
        return knifeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_code
     *
     * @param knifeCode the value for knife_template.knife_code
     *
     * @mbggenerated
     */
    public void setKnifeCode(String knifeCode) {
        this.knifeCode = knifeCode == null ? null : knifeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knife_template.knife_picture
     *
     * @return the value of knife_template.knife_picture
     *
     * @mbggenerated
     */
    public String getKnifePicture() {
        return knifePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knife_template.knife_picture
     *
     * @param knifePicture the value for knife_template.knife_picture
     *
     * @mbggenerated
     */
    public void setKnifePicture(String knifePicture) {
        this.knifePicture = knifePicture == null ? null : knifePicture.trim();
    }

    public MultipartFile getKnifePictureFile() {
        return knifePictureFile;
    }

    public void setKnifePictureFile(MultipartFile knifePictureFile) {
        this.knifePictureFile = knifePictureFile;
    }
}