package com.generator.pojo;

public class MaterialPurchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.purchase_id
     *
     * @mbggenerated
     */
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.spec
     *
     * @mbggenerated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.is_end
     *
     * @mbggenerated
     */
    private Integer isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.to_num
     *
     * @mbggenerated
     */
    private Integer toNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.is_ticket
     *
     * @mbggenerated
     */
    private Integer isTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_purchase.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.purchase_id
     *
     * @return the value of material_purchase.purchase_id
     *
     * @mbggenerated
     */
    public Integer getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.purchase_id
     *
     * @param purchaseId the value for material_purchase.purchase_id
     *
     * @mbggenerated
     */
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.material_name
     *
     * @return the value of material_purchase.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.material_name
     *
     * @param materialName the value for material_purchase.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.spec
     *
     * @return the value of material_purchase.spec
     *
     * @mbggenerated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.spec
     *
     * @param spec the value for material_purchase.spec
     *
     * @mbggenerated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.price
     *
     * @return the value of material_purchase.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.price
     *
     * @param price the value for material_purchase.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.num
     *
     * @return the value of material_purchase.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.num
     *
     * @param num the value for material_purchase.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.money
     *
     * @return the value of material_purchase.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.money
     *
     * @param money the value for material_purchase.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.supplier_name
     *
     * @return the value of material_purchase.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.supplier_name
     *
     * @param supplierName the value for material_purchase.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.time
     *
     * @return the value of material_purchase.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.time
     *
     * @param time the value for material_purchase.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.is_end
     *
     * @return the value of material_purchase.is_end
     *
     * @mbggenerated
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.is_end
     *
     * @param isEnd the value for material_purchase.is_end
     *
     * @mbggenerated
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.to_num
     *
     * @return the value of material_purchase.to_num
     *
     * @mbggenerated
     */
    public Integer getToNum() {
        return toNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.to_num
     *
     * @param toNum the value for material_purchase.to_num
     *
     * @mbggenerated
     */
    public void setToNum(Integer toNum) {
        this.toNum = toNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.is_ticket
     *
     * @return the value of material_purchase.is_ticket
     *
     * @mbggenerated
     */
    public Integer getIsTicket() {
        return isTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.is_ticket
     *
     * @param isTicket the value for material_purchase.is_ticket
     *
     * @mbggenerated
     */
    public void setIsTicket(Integer isTicket) {
        this.isTicket = isTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.remarks
     *
     * @return the value of material_purchase.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.remarks
     *
     * @param remarks the value for material_purchase.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.state
     *
     * @return the value of material_purchase.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.state
     *
     * @param state the value for material_purchase.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_purchase.fake
     *
     * @return the value of material_purchase.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_purchase.fake
     *
     * @param fake the value for material_purchase.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}