package com.generator.pojo;

public class MaterialStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.making_storage_id
     *
     * @mbggenerated
     */
    private Integer makingStorageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.making_name
     *
     * @mbggenerated
     */
    private String makingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.storage_spec
     *
     * @mbggenerated
     */
    private String storageSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.total
     *
     * @mbggenerated
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.storage_name
     *
     * @mbggenerated
     */
    private String storageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_storage.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.making_storage_id
     *
     * @return the value of material_storage.making_storage_id
     *
     * @mbggenerated
     */
    public Integer getMakingStorageId() {
        return makingStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.making_storage_id
     *
     * @param makingStorageId the value for material_storage.making_storage_id
     *
     * @mbggenerated
     */
    public void setMakingStorageId(Integer makingStorageId) {
        this.makingStorageId = makingStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.making_name
     *
     * @return the value of material_storage.making_name
     *
     * @mbggenerated
     */
    public String getMakingName() {
        return makingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.making_name
     *
     * @param makingName the value for material_storage.making_name
     *
     * @mbggenerated
     */
    public void setMakingName(String makingName) {
        this.makingName = makingName == null ? null : makingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.storage_spec
     *
     * @return the value of material_storage.storage_spec
     *
     * @mbggenerated
     */
    public String getStorageSpec() {
        return storageSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.storage_spec
     *
     * @param storageSpec the value for material_storage.storage_spec
     *
     * @mbggenerated
     */
    public void setStorageSpec(String storageSpec) {
        this.storageSpec = storageSpec == null ? null : storageSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.num
     *
     * @return the value of material_storage.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.num
     *
     * @param num the value for material_storage.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.price
     *
     * @return the value of material_storage.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.price
     *
     * @param price the value for material_storage.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.total
     *
     * @return the value of material_storage.total
     *
     * @mbggenerated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.total
     *
     * @param total the value for material_storage.total
     *
     * @mbggenerated
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.time
     *
     * @return the value of material_storage.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.time
     *
     * @param time the value for material_storage.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.storage_name
     *
     * @return the value of material_storage.storage_name
     *
     * @mbggenerated
     */
    public String getStorageName() {
        return storageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.storage_name
     *
     * @param storageName the value for material_storage.storage_name
     *
     * @mbggenerated
     */
    public void setStorageName(String storageName) {
        this.storageName = storageName == null ? null : storageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.type
     *
     * @return the value of material_storage.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.type
     *
     * @param type the value for material_storage.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_storage.fake
     *
     * @return the value of material_storage.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_storage.fake
     *
     * @param fake the value for material_storage.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}