package com.generator.pojo;

public class PaperSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_setting.paper_id
     *
     * @mbggenerated
     */
    private Integer paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_setting.paper_name
     *
     * @mbggenerated
     */
    private String paperName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_setting.paper_code
     *
     * @mbggenerated
     */
    private String paperCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_setting.paper_weight
     *
     * @mbggenerated
     */
    private Integer paperWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_setting.paper_price
     *
     * @mbggenerated
     */
    private Double paperPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_setting.paper_id
     *
     * @return the value of paper_setting.paper_id
     *
     * @mbggenerated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_setting.paper_id
     *
     * @param paperId the value for paper_setting.paper_id
     *
     * @mbggenerated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_setting.paper_name
     *
     * @return the value of paper_setting.paper_name
     *
     * @mbggenerated
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_setting.paper_name
     *
     * @param paperName the value for paper_setting.paper_name
     *
     * @mbggenerated
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName == null ? null : paperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_setting.paper_code
     *
     * @return the value of paper_setting.paper_code
     *
     * @mbggenerated
     */
    public String getPaperCode() {
        return paperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_setting.paper_code
     *
     * @param paperCode the value for paper_setting.paper_code
     *
     * @mbggenerated
     */
    public void setPaperCode(String paperCode) {
        this.paperCode = paperCode == null ? null : paperCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_setting.paper_weight
     *
     * @return the value of paper_setting.paper_weight
     *
     * @mbggenerated
     */
    public Integer getPaperWeight() {
        return paperWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_setting.paper_weight
     *
     * @param paperWeight the value for paper_setting.paper_weight
     *
     * @mbggenerated
     */
    public void setPaperWeight(Integer paperWeight) {
        this.paperWeight = paperWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_setting.paper_price
     *
     * @return the value of paper_setting.paper_price
     *
     * @mbggenerated
     */
    public Double getPaperPrice() {
        return paperPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_setting.paper_price
     *
     * @param paperPrice the value for paper_setting.paper_price
     *
     * @mbggenerated
     */
    public void setPaperPrice(Double paperPrice) {
        this.paperPrice = paperPrice;
    }
}