package com.generator.pojo;

public class PaperChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.paper_change_id
     *
     * @mbggenerated
     */
    private Integer paperChangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.paper_change_s
     *
     * @mbggenerated
     */
    private String paperChangeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.paper_change_price
     *
     * @mbggenerated
     */
    private Double paperChangePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper_change.paper_change_e
     *
     * @mbggenerated
     */
    private String paperChangeE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.paper_change_id
     *
     * @return the value of paper_change.paper_change_id
     *
     * @mbggenerated
     */
    public Integer getPaperChangeId() {
        return paperChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.paper_change_id
     *
     * @param paperChangeId the value for paper_change.paper_change_id
     *
     * @mbggenerated
     */
    public void setPaperChangeId(Integer paperChangeId) {
        this.paperChangeId = paperChangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.supplier_id
     *
     * @return the value of paper_change.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.supplier_id
     *
     * @param supplierId the value for paper_change.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.paper_change_s
     *
     * @return the value of paper_change.paper_change_s
     *
     * @mbggenerated
     */
    public String getPaperChangeS() {
        return paperChangeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.paper_change_s
     *
     * @param paperChangeS the value for paper_change.paper_change_s
     *
     * @mbggenerated
     */
    public void setPaperChangeS(String paperChangeS) {
        this.paperChangeS = paperChangeS == null ? null : paperChangeS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.paper_change_price
     *
     * @return the value of paper_change.paper_change_price
     *
     * @mbggenerated
     */
    public Double getPaperChangePrice() {
        return paperChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.paper_change_price
     *
     * @param paperChangePrice the value for paper_change.paper_change_price
     *
     * @mbggenerated
     */
    public void setPaperChangePrice(Double paperChangePrice) {
        this.paperChangePrice = paperChangePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.fake
     *
     * @return the value of paper_change.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.fake
     *
     * @param fake the value for paper_change.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper_change.paper_change_e
     *
     * @return the value of paper_change.paper_change_e
     *
     * @mbggenerated
     */
    public String getPaperChangeE() {
        return paperChangeE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper_change.paper_change_e
     *
     * @param paperChangeE the value for paper_change.paper_change_e
     *
     * @mbggenerated
     */
    public void setPaperChangeE(String paperChangeE) {
        this.paperChangeE = paperChangeE == null ? null : paperChangeE.trim();
    }
}