package com.generator.pojo;

import java.util.Date;

public class PayableAdjustment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_id
     *
     * @mbggenerated
     */
    private Integer payableAdjustmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_remarks
     *
     * @mbggenerated
     */
    private String payableAdjustmentRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_date
     *
     * @mbggenerated
     */
    private Date payableAdjustmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_price
     *
     * @mbggenerated
     */
    private Double payableAdjustmentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_after_price
     *
     * @mbggenerated
     */
    private Double payableAdjustmentAfterPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_total
     *
     * @mbggenerated
     */
    private Double payableAdjustmentTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_after_total
     *
     * @mbggenerated
     */
    private Double payableAdjustmentAfterTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.payable_adjustment_type
     *
     * @mbggenerated
     */
    private Double payableAdjustmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.vendor_name
     *
     * @mbggenerated
     */
    private String vendorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payable_adjustment.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_id
     *
     * @return the value of payable_adjustment.payable_adjustment_id
     *
     * @mbggenerated
     */
    public Integer getPayableAdjustmentId() {
        return payableAdjustmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_id
     *
     * @param payableAdjustmentId the value for payable_adjustment.payable_adjustment_id
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentId(Integer payableAdjustmentId) {
        this.payableAdjustmentId = payableAdjustmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_remarks
     *
     * @return the value of payable_adjustment.payable_adjustment_remarks
     *
     * @mbggenerated
     */
    public String getPayableAdjustmentRemarks() {
        return payableAdjustmentRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_remarks
     *
     * @param payableAdjustmentRemarks the value for payable_adjustment.payable_adjustment_remarks
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentRemarks(String payableAdjustmentRemarks) {
        this.payableAdjustmentRemarks = payableAdjustmentRemarks == null ? null : payableAdjustmentRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_date
     *
     * @return the value of payable_adjustment.payable_adjustment_date
     *
     * @mbggenerated
     */
    public Date getPayableAdjustmentDate() {
        return payableAdjustmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_date
     *
     * @param payableAdjustmentDate the value for payable_adjustment.payable_adjustment_date
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentDate(Date payableAdjustmentDate) {
        this.payableAdjustmentDate = payableAdjustmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_price
     *
     * @return the value of payable_adjustment.payable_adjustment_price
     *
     * @mbggenerated
     */
    public Double getPayableAdjustmentPrice() {
        return payableAdjustmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_price
     *
     * @param payableAdjustmentPrice the value for payable_adjustment.payable_adjustment_price
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentPrice(Double payableAdjustmentPrice) {
        this.payableAdjustmentPrice = payableAdjustmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_after_price
     *
     * @return the value of payable_adjustment.payable_adjustment_after_price
     *
     * @mbggenerated
     */
    public Double getPayableAdjustmentAfterPrice() {
        return payableAdjustmentAfterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_after_price
     *
     * @param payableAdjustmentAfterPrice the value for payable_adjustment.payable_adjustment_after_price
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentAfterPrice(Double payableAdjustmentAfterPrice) {
        this.payableAdjustmentAfterPrice = payableAdjustmentAfterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_total
     *
     * @return the value of payable_adjustment.payable_adjustment_total
     *
     * @mbggenerated
     */
    public Double getPayableAdjustmentTotal() {
        return payableAdjustmentTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_total
     *
     * @param payableAdjustmentTotal the value for payable_adjustment.payable_adjustment_total
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentTotal(Double payableAdjustmentTotal) {
        this.payableAdjustmentTotal = payableAdjustmentTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_after_total
     *
     * @return the value of payable_adjustment.payable_adjustment_after_total
     *
     * @mbggenerated
     */
    public Double getPayableAdjustmentAfterTotal() {
        return payableAdjustmentAfterTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_after_total
     *
     * @param payableAdjustmentAfterTotal the value for payable_adjustment.payable_adjustment_after_total
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentAfterTotal(Double payableAdjustmentAfterTotal) {
        this.payableAdjustmentAfterTotal = payableAdjustmentAfterTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.payable_adjustment_type
     *
     * @return the value of payable_adjustment.payable_adjustment_type
     *
     * @mbggenerated
     */
    public Double getPayableAdjustmentType() {
        return payableAdjustmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.payable_adjustment_type
     *
     * @param payableAdjustmentType the value for payable_adjustment.payable_adjustment_type
     *
     * @mbggenerated
     */
    public void setPayableAdjustmentType(Double payableAdjustmentType) {
        this.payableAdjustmentType = payableAdjustmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.vendor_name
     *
     * @return the value of payable_adjustment.vendor_name
     *
     * @mbggenerated
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.vendor_name
     *
     * @param vendorName the value for payable_adjustment.vendor_name
     *
     * @mbggenerated
     */
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName == null ? null : vendorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.order_number
     *
     * @return the value of payable_adjustment.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.order_number
     *
     * @param orderNumber the value for payable_adjustment.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.customer
     *
     * @return the value of payable_adjustment.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.customer
     *
     * @param customer the value for payable_adjustment.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payable_adjustment.product_name
     *
     * @return the value of payable_adjustment.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payable_adjustment.product_name
     *
     * @param productName the value for payable_adjustment.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }
}