package com.generator.pojo;

public class Place {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.custom_id
     *
     * @mbggenerated
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.custom_company
     *
     * @mbggenerated
     */
    private String customCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.custom_tel
     *
     * @mbggenerated
     */
    private String customTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.delivery_time
     *
     * @mbggenerated
     */
    private String deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.delivery_address
     *
     * @mbggenerated
     */
    private String deliveryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.order_time
     *
     * @mbggenerated
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_name
     *
     * @mbggenerated
     */
    private String cartonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_number
     *
     * @mbggenerated
     */
    private String cartonNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_spec
     *
     * @mbggenerated
     */
    private String cartonSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.is_sample_box
     *
     * @mbggenerated
     */
    private Integer isSampleBox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_id
     *
     * @mbggenerated
     */
    private Integer cartonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_type
     *
     * @mbggenerated
     */
    private String cartonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_length
     *
     * @mbggenerated
     */
    private Double cartonLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_width
     *
     * @mbggenerated
     */
    private Double cartonWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_height
     *
     * @mbggenerated
     */
    private Double cartonHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.blanking_length
     *
     * @mbggenerated
     */
    private Double blankingLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.blanking_width
     *
     * @mbggenerated
     */
    private Double blankingWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_unit
     *
     * @mbggenerated
     */
    private String cartonUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.material_science
     *
     * @mbggenerated
     */
    private String materialScience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.cardboard_length
     *
     * @mbggenerated
     */
    private Double cardboardLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.cardboard_width
     *
     * @mbggenerated
     */
    private Double cardboardWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.pit_id
     *
     * @mbggenerated
     */
    private Integer pitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.pit_type
     *
     * @mbggenerated
     */
    private String pitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_color
     *
     * @mbggenerated
     */
    private String cartonColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.combination_mode
     *
     * @mbggenerated
     */
    private String combinationMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.nailing_num
     *
     * @mbggenerated
     */
    private Integer nailingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.fabric_width
     *
     * @mbggenerated
     */
    private Double fabricWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.fabric_bei
     *
     * @mbggenerated
     */
    private Integer fabricBei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.working_procedure
     *
     * @mbggenerated
     */
    private String workingProcedure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.plate_id
     *
     * @mbggenerated
     */
    private String plateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.plate_name
     *
     * @mbggenerated
     */
    private String plateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.knife_picture
     *
     * @mbggenerated
     */
    private String knifePicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.plates_id
     *
     * @mbggenerated
     */
    private String platesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.plates_name
     *
     * @mbggenerated
     */
    private String platesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.printing_image
     *
     * @mbggenerated
     */
    private String printingImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_image
     *
     * @mbggenerated
     */
    private String cartonImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.line_type
     *
     * @mbggenerated
     */
    private Integer lineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.pack_num
     *
     * @mbggenerated
     */
    private Integer packNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_price
     *
     * @mbggenerated
     */
    private Double cartonPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.carton_total
     *
     * @mbggenerated
     */
    private Double cartonTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.profit
     *
     * @mbggenerated
     */
    private Double profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.cost
     *
     * @mbggenerated
     */
    private Double cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.square_of_cardboard
     *
     * @mbggenerated
     */
    private Double squareOfCardboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.square_of_cardboard_T
     *
     * @mbggenerated
     */
    private Double squareOfCardboardT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.length_line
     *
     * @mbggenerated
     */
    private String lengthLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.width_line
     *
     * @mbggenerated
     */
    private String widthLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.open_number
     *
     * @mbggenerated
     */
    private String openNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.size_type
     *
     * @mbggenerated
     */
    private Integer sizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.number_of_spare_parts
     *
     * @mbggenerated
     */
    private Integer numberOfSpareParts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.maker_remarks
     *
     * @mbggenerated
     */
    private String makerRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.delivery_remarks
     *
     * @mbggenerated
     */
    private String deliveryRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.purchase_remarks
     *
     * @mbggenerated
     */
    private String purchaseRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.order_identification
     *
     * @mbggenerated
     */
    private Integer orderIdentification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.order_state
     *
     * @mbggenerated
     */
    private Integer orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.is_library
     *
     * @mbggenerated
     */
    private Integer isLibrary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.contract_number
     *
     * @mbggenerated
     */
    private String contractNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.cutting_num
     *
     * @mbggenerated
     */
    private String cuttingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.long_edge
     *
     * @mbggenerated
     */
    private Double longEdge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column place.wide_edge
     *
     * @mbggenerated
     */
    private Double wideEdge;

    private Double supplierPrice;//纸板供应商单平方价装填
    private Double unitPrice;//纸板供应商单价装填
    private String supplierMaterial;//纸板供应商材质装填

    private Integer num;//纸板采购数装填

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public Double getSupplierPrice() {
        return supplierPrice;
    }

    public void setSupplierPrice(Double supplierPrice) {
        this.supplierPrice = supplierPrice;
    }

    public String getSupplierMaterial() {
        return supplierMaterial;
    }

    public void setSupplierMaterial(String supplierMaterial) {
        this.supplierMaterial = supplierMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.id
     *
     * @return the value of place.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.id
     *
     * @param id the value for place.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.order_account
     *
     * @return the value of place.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.order_account
     *
     * @param orderAccount the value for place.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.custom_id
     *
     * @return the value of place.custom_id
     *
     * @mbggenerated
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.custom_id
     *
     * @param customId the value for place.custom_id
     *
     * @mbggenerated
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.custom_name
     *
     * @return the value of place.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.custom_name
     *
     * @param customName the value for place.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.custom_company
     *
     * @return the value of place.custom_company
     *
     * @mbggenerated
     */
    public String getCustomCompany() {
        return customCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.custom_company
     *
     * @param customCompany the value for place.custom_company
     *
     * @mbggenerated
     */
    public void setCustomCompany(String customCompany) {
        this.customCompany = customCompany == null ? null : customCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.custom_tel
     *
     * @return the value of place.custom_tel
     *
     * @mbggenerated
     */
    public String getCustomTel() {
        return customTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.custom_tel
     *
     * @param customTel the value for place.custom_tel
     *
     * @mbggenerated
     */
    public void setCustomTel(String customTel) {
        this.customTel = customTel == null ? null : customTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.staff_id
     *
     * @return the value of place.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.staff_id
     *
     * @param staffId the value for place.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.delivery_time
     *
     * @return the value of place.delivery_time
     *
     * @mbggenerated
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.delivery_time
     *
     * @param deliveryTime the value for place.delivery_time
     *
     * @mbggenerated
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.delivery_address
     *
     * @return the value of place.delivery_address
     *
     * @mbggenerated
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.delivery_address
     *
     * @param deliveryAddress the value for place.delivery_address
     *
     * @mbggenerated
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress == null ? null : deliveryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.order_num
     *
     * @return the value of place.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.order_num
     *
     * @param orderNum the value for place.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.order_time
     *
     * @return the value of place.order_time
     *
     * @mbggenerated
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.order_time
     *
     * @param orderTime the value for place.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_name
     *
     * @return the value of place.carton_name
     *
     * @mbggenerated
     */
    public String getCartonName() {
        return cartonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_name
     *
     * @param cartonName the value for place.carton_name
     *
     * @mbggenerated
     */
    public void setCartonName(String cartonName) {
        this.cartonName = cartonName == null ? null : cartonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_number
     *
     * @return the value of place.carton_number
     *
     * @mbggenerated
     */
    public String getCartonNumber() {
        return cartonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_number
     *
     * @param cartonNumber the value for place.carton_number
     *
     * @mbggenerated
     */
    public void setCartonNumber(String cartonNumber) {
        this.cartonNumber = cartonNumber == null ? null : cartonNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_spec
     *
     * @return the value of place.carton_spec
     *
     * @mbggenerated
     */
    public String getCartonSpec() {
        return cartonSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_spec
     *
     * @param cartonSpec the value for place.carton_spec
     *
     * @mbggenerated
     */
    public void setCartonSpec(String cartonSpec) {
        this.cartonSpec = cartonSpec == null ? null : cartonSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.is_sample_box
     *
     * @return the value of place.is_sample_box
     *
     * @mbggenerated
     */
    public Integer getIsSampleBox() {
        return isSampleBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.is_sample_box
     *
     * @param isSampleBox the value for place.is_sample_box
     *
     * @mbggenerated
     */
    public void setIsSampleBox(Integer isSampleBox) {
        this.isSampleBox = isSampleBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_id
     *
     * @return the value of place.carton_id
     *
     * @mbggenerated
     */
    public Integer getCartonId() {
        return cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_id
     *
     * @param cartonId the value for place.carton_id
     *
     * @mbggenerated
     */
    public void setCartonId(Integer cartonId) {
        this.cartonId = cartonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_type
     *
     * @return the value of place.carton_type
     *
     * @mbggenerated
     */
    public String getCartonType() {
        return cartonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_type
     *
     * @param cartonType the value for place.carton_type
     *
     * @mbggenerated
     */
    public void setCartonType(String cartonType) {
        this.cartonType = cartonType == null ? null : cartonType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_length
     *
     * @return the value of place.carton_length
     *
     * @mbggenerated
     */
    public Double getCartonLength() {
        return cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_length
     *
     * @param cartonLength the value for place.carton_length
     *
     * @mbggenerated
     */
    public void setCartonLength(Double cartonLength) {
        this.cartonLength = cartonLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_width
     *
     * @return the value of place.carton_width
     *
     * @mbggenerated
     */
    public Double getCartonWidth() {
        return cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_width
     *
     * @param cartonWidth the value for place.carton_width
     *
     * @mbggenerated
     */
    public void setCartonWidth(Double cartonWidth) {
        this.cartonWidth = cartonWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_height
     *
     * @return the value of place.carton_height
     *
     * @mbggenerated
     */
    public Double getCartonHeight() {
        return cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_height
     *
     * @param cartonHeight the value for place.carton_height
     *
     * @mbggenerated
     */
    public void setCartonHeight(Double cartonHeight) {
        this.cartonHeight = cartonHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.blanking_length
     *
     * @return the value of place.blanking_length
     *
     * @mbggenerated
     */
    public Double getBlankingLength() {
        return blankingLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.blanking_length
     *
     * @param blankingLength the value for place.blanking_length
     *
     * @mbggenerated
     */
    public void setBlankingLength(Double blankingLength) {
        this.blankingLength = blankingLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.blanking_width
     *
     * @return the value of place.blanking_width
     *
     * @mbggenerated
     */
    public Double getBlankingWidth() {
        return blankingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.blanking_width
     *
     * @param blankingWidth the value for place.blanking_width
     *
     * @mbggenerated
     */
    public void setBlankingWidth(Double blankingWidth) {
        this.blankingWidth = blankingWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_unit
     *
     * @return the value of place.carton_unit
     *
     * @mbggenerated
     */
    public String getCartonUnit() {
        return cartonUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_unit
     *
     * @param cartonUnit the value for place.carton_unit
     *
     * @mbggenerated
     */
    public void setCartonUnit(String cartonUnit) {
        this.cartonUnit = cartonUnit == null ? null : cartonUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.material_science
     *
     * @return the value of place.material_science
     *
     * @mbggenerated
     */
    public String getMaterialScience() {
        return materialScience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.material_science
     *
     * @param materialScience the value for place.material_science
     *
     * @mbggenerated
     */
    public void setMaterialScience(String materialScience) {
        this.materialScience = materialScience == null ? null : materialScience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.cardboard_length
     *
     * @return the value of place.cardboard_length
     *
     * @mbggenerated
     */
    public Double getCardboardLength() {
        return cardboardLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.cardboard_length
     *
     * @param cardboardLength the value for place.cardboard_length
     *
     * @mbggenerated
     */
    public void setCardboardLength(Double cardboardLength) {
        this.cardboardLength = cardboardLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.cardboard_width
     *
     * @return the value of place.cardboard_width
     *
     * @mbggenerated
     */
    public Double getCardboardWidth() {
        return cardboardWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.cardboard_width
     *
     * @param cardboardWidth the value for place.cardboard_width
     *
     * @mbggenerated
     */
    public void setCardboardWidth(Double cardboardWidth) {
        this.cardboardWidth = cardboardWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.pit_id
     *
     * @return the value of place.pit_id
     *
     * @mbggenerated
     */
    public Integer getPitId() {
        return pitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.pit_id
     *
     * @param pitId the value for place.pit_id
     *
     * @mbggenerated
     */
    public void setPitId(Integer pitId) {
        this.pitId = pitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.pit_type
     *
     * @return the value of place.pit_type
     *
     * @mbggenerated
     */
    public String getPitType() {
        return pitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.pit_type
     *
     * @param pitType the value for place.pit_type
     *
     * @mbggenerated
     */
    public void setPitType(String pitType) {
        this.pitType = pitType == null ? null : pitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_color
     *
     * @return the value of place.carton_color
     *
     * @mbggenerated
     */
    public String getCartonColor() {
        return cartonColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_color
     *
     * @param cartonColor the value for place.carton_color
     *
     * @mbggenerated
     */
    public void setCartonColor(String cartonColor) {
        this.cartonColor = cartonColor == null ? null : cartonColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.combination_mode
     *
     * @return the value of place.combination_mode
     *
     * @mbggenerated
     */
    public String getCombinationMode() {
        return combinationMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.combination_mode
     *
     * @param combinationMode the value for place.combination_mode
     *
     * @mbggenerated
     */
    public void setCombinationMode(String combinationMode) {
        this.combinationMode = combinationMode == null ? null : combinationMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.nailing_num
     *
     * @return the value of place.nailing_num
     *
     * @mbggenerated
     */
    public Integer getNailingNum() {
        return nailingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.nailing_num
     *
     * @param nailingNum the value for place.nailing_num
     *
     * @mbggenerated
     */
    public void setNailingNum(Integer nailingNum) {
        this.nailingNum = nailingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.fabric_width
     *
     * @return the value of place.fabric_width
     *
     * @mbggenerated
     */
    public Double getFabricWidth() {
        return fabricWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.fabric_width
     *
     * @param fabricWidth the value for place.fabric_width
     *
     * @mbggenerated
     */
    public void setFabricWidth(Double fabricWidth) {
        this.fabricWidth = fabricWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.fabric_bei
     *
     * @return the value of place.fabric_bei
     *
     * @mbggenerated
     */
    public Integer getFabricBei() {
        return fabricBei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.fabric_bei
     *
     * @param fabricBei the value for place.fabric_bei
     *
     * @mbggenerated
     */
    public void setFabricBei(Integer fabricBei) {
        this.fabricBei = fabricBei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.working_procedure
     *
     * @return the value of place.working_procedure
     *
     * @mbggenerated
     */
    public String getWorkingProcedure() {
        return workingProcedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.working_procedure
     *
     * @param workingProcedure the value for place.working_procedure
     *
     * @mbggenerated
     */
    public void setWorkingProcedure(String workingProcedure) {
        this.workingProcedure = workingProcedure == null ? null : workingProcedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.plate_id
     *
     * @return the value of place.plate_id
     *
     * @mbggenerated
     */
    public String getPlateId() {
        return plateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.plate_id
     *
     * @param plateId the value for place.plate_id
     *
     * @mbggenerated
     */
    public void setPlateId(String plateId) {
        this.plateId = plateId == null ? null : plateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.plate_name
     *
     * @return the value of place.plate_name
     *
     * @mbggenerated
     */
    public String getPlateName() {
        return plateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.plate_name
     *
     * @param plateName the value for place.plate_name
     *
     * @mbggenerated
     */
    public void setPlateName(String plateName) {
        this.plateName = plateName == null ? null : plateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.knife_picture
     *
     * @return the value of place.knife_picture
     *
     * @mbggenerated
     */
    public String getKnifePicture() {
        return knifePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.knife_picture
     *
     * @param knifePicture the value for place.knife_picture
     *
     * @mbggenerated
     */
    public void setKnifePicture(String knifePicture) {
        this.knifePicture = knifePicture == null ? null : knifePicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.plates_id
     *
     * @return the value of place.plates_id
     *
     * @mbggenerated
     */
    public String getPlatesId() {
        return platesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.plates_id
     *
     * @param platesId the value for place.plates_id
     *
     * @mbggenerated
     */
    public void setPlatesId(String platesId) {
        this.platesId = platesId == null ? null : platesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.plates_name
     *
     * @return the value of place.plates_name
     *
     * @mbggenerated
     */
    public String getPlatesName() {
        return platesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.plates_name
     *
     * @param platesName the value for place.plates_name
     *
     * @mbggenerated
     */
    public void setPlatesName(String platesName) {
        this.platesName = platesName == null ? null : platesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.printing_image
     *
     * @return the value of place.printing_image
     *
     * @mbggenerated
     */
    public String getPrintingImage() {
        return printingImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.printing_image
     *
     * @param printingImage the value for place.printing_image
     *
     * @mbggenerated
     */
    public void setPrintingImage(String printingImage) {
        this.printingImage = printingImage == null ? null : printingImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_image
     *
     * @return the value of place.carton_image
     *
     * @mbggenerated
     */
    public String getCartonImage() {
        return cartonImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_image
     *
     * @param cartonImage the value for place.carton_image
     *
     * @mbggenerated
     */
    public void setCartonImage(String cartonImage) {
        this.cartonImage = cartonImage == null ? null : cartonImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.line_type
     *
     * @return the value of place.line_type
     *
     * @mbggenerated
     */
    public Integer getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.line_type
     *
     * @param lineType the value for place.line_type
     *
     * @mbggenerated
     */
    public void setLineType(Integer lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.pack_num
     *
     * @return the value of place.pack_num
     *
     * @mbggenerated
     */
    public Integer getPackNum() {
        return packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.pack_num
     *
     * @param packNum the value for place.pack_num
     *
     * @mbggenerated
     */
    public void setPackNum(Integer packNum) {
        this.packNum = packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_price
     *
     * @return the value of place.carton_price
     *
     * @mbggenerated
     */
    public Double getCartonPrice() {
        return cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_price
     *
     * @param cartonPrice the value for place.carton_price
     *
     * @mbggenerated
     */
    public void setCartonPrice(Double cartonPrice) {
        this.cartonPrice = cartonPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.carton_total
     *
     * @return the value of place.carton_total
     *
     * @mbggenerated
     */
    public Double getCartonTotal() {
        return cartonTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.carton_total
     *
     * @param cartonTotal the value for place.carton_total
     *
     * @mbggenerated
     */
    public void setCartonTotal(Double cartonTotal) {
        this.cartonTotal = cartonTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.profit
     *
     * @return the value of place.profit
     *
     * @mbggenerated
     */
    public Double getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.profit
     *
     * @param profit the value for place.profit
     *
     * @mbggenerated
     */
    public void setProfit(Double profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.cost
     *
     * @return the value of place.cost
     *
     * @mbggenerated
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.cost
     *
     * @param cost the value for place.cost
     *
     * @mbggenerated
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.square_of_cardboard
     *
     * @return the value of place.square_of_cardboard
     *
     * @mbggenerated
     */
    public Double getSquareOfCardboard() {
        return squareOfCardboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.square_of_cardboard
     *
     * @param squareOfCardboard the value for place.square_of_cardboard
     *
     * @mbggenerated
     */
    public void setSquareOfCardboard(Double squareOfCardboard) {
        this.squareOfCardboard = squareOfCardboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.square_of_cardboard_T
     *
     * @return the value of place.square_of_cardboard_T
     *
     * @mbggenerated
     */
    public Double getSquareOfCardboardT() {
        return squareOfCardboardT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.square_of_cardboard_T
     *
     * @param squareOfCardboardT the value for place.square_of_cardboard_T
     *
     * @mbggenerated
     */
    public void setSquareOfCardboardT(Double squareOfCardboardT) {
        this.squareOfCardboardT = squareOfCardboardT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.length_line
     *
     * @return the value of place.length_line
     *
     * @mbggenerated
     */
    public String getLengthLine() {
        return lengthLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.length_line
     *
     * @param lengthLine the value for place.length_line
     *
     * @mbggenerated
     */
    public void setLengthLine(String lengthLine) {
        this.lengthLine = lengthLine == null ? null : lengthLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.width_line
     *
     * @return the value of place.width_line
     *
     * @mbggenerated
     */
    public String getWidthLine() {
        return widthLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.width_line
     *
     * @param widthLine the value for place.width_line
     *
     * @mbggenerated
     */
    public void setWidthLine(String widthLine) {
        this.widthLine = widthLine == null ? null : widthLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.open_number
     *
     * @return the value of place.open_number
     *
     * @mbggenerated
     */
    public String getOpenNumber() {
        return openNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.open_number
     *
     * @param openNumber the value for place.open_number
     *
     * @mbggenerated
     */
    public void setOpenNumber(String openNumber) {
        this.openNumber = openNumber == null ? null : openNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.size_type
     *
     * @return the value of place.size_type
     *
     * @mbggenerated
     */
    public Integer getSizeType() {
        return sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.size_type
     *
     * @param sizeType the value for place.size_type
     *
     * @mbggenerated
     */
    public void setSizeType(Integer sizeType) {
        this.sizeType = sizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.number_of_spare_parts
     *
     * @return the value of place.number_of_spare_parts
     *
     * @mbggenerated
     */
    public Integer getNumberOfSpareParts() {
        return numberOfSpareParts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.number_of_spare_parts
     *
     * @param numberOfSpareParts the value for place.number_of_spare_parts
     *
     * @mbggenerated
     */
    public void setNumberOfSpareParts(Integer numberOfSpareParts) {
        this.numberOfSpareParts = numberOfSpareParts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.maker_remarks
     *
     * @return the value of place.maker_remarks
     *
     * @mbggenerated
     */
    public String getMakerRemarks() {
        return makerRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.maker_remarks
     *
     * @param makerRemarks the value for place.maker_remarks
     *
     * @mbggenerated
     */
    public void setMakerRemarks(String makerRemarks) {
        this.makerRemarks = makerRemarks == null ? null : makerRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.delivery_remarks
     *
     * @return the value of place.delivery_remarks
     *
     * @mbggenerated
     */
    public String getDeliveryRemarks() {
        return deliveryRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.delivery_remarks
     *
     * @param deliveryRemarks the value for place.delivery_remarks
     *
     * @mbggenerated
     */
    public void setDeliveryRemarks(String deliveryRemarks) {
        this.deliveryRemarks = deliveryRemarks == null ? null : deliveryRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.purchase_remarks
     *
     * @return the value of place.purchase_remarks
     *
     * @mbggenerated
     */
    public String getPurchaseRemarks() {
        return purchaseRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.purchase_remarks
     *
     * @param purchaseRemarks the value for place.purchase_remarks
     *
     * @mbggenerated
     */
    public void setPurchaseRemarks(String purchaseRemarks) {
        this.purchaseRemarks = purchaseRemarks == null ? null : purchaseRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.order_identification
     *
     * @return the value of place.order_identification
     *
     * @mbggenerated
     */
    public Integer getOrderIdentification() {
        return orderIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.order_identification
     *
     * @param orderIdentification the value for place.order_identification
     *
     * @mbggenerated
     */
    public void setOrderIdentification(Integer orderIdentification) {
        this.orderIdentification = orderIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.order_state
     *
     * @return the value of place.order_state
     *
     * @mbggenerated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.order_state
     *
     * @param orderState the value for place.order_state
     *
     * @mbggenerated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.is_library
     *
     * @return the value of place.is_library
     *
     * @mbggenerated
     */
    public Integer getIsLibrary() {
        return isLibrary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.is_library
     *
     * @param isLibrary the value for place.is_library
     *
     * @mbggenerated
     */
    public void setIsLibrary(Integer isLibrary) {
        this.isLibrary = isLibrary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.fake
     *
     * @return the value of place.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.fake
     *
     * @param fake the value for place.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.contract_number
     *
     * @return the value of place.contract_number
     *
     * @mbggenerated
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.contract_number
     *
     * @param contractNumber the value for place.contract_number
     *
     * @mbggenerated
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber == null ? null : contractNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.cutting_num
     *
     * @return the value of place.cutting_num
     *
     * @mbggenerated
     */
    public String getCuttingNum() {
        return cuttingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.cutting_num
     *
     * @param cuttingNum the value for place.cutting_num
     *
     * @mbggenerated
     */
    public void setCuttingNum(String cuttingNum) {
        this.cuttingNum = cuttingNum == null ? null : cuttingNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.long_edge
     *
     * @return the value of place.long_edge
     *
     * @mbggenerated
     */
    public Double getLongEdge() {
        return longEdge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.long_edge
     *
     * @param longEdge the value for place.long_edge
     *
     * @mbggenerated
     */
    public void setLongEdge(Double longEdge) {
        this.longEdge = longEdge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column place.wide_edge
     *
     * @return the value of place.wide_edge
     *
     * @mbggenerated
     */
    public Double getWideEdge() {
        return wideEdge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column place.wide_edge
     *
     * @param wideEdge the value for place.wide_edge
     *
     * @mbggenerated
     */
    public void setWideEdge(Double wideEdge) {
        this.wideEdge = wideEdge;
    }
}