package com.generator.pojo;

import org.springframework.web.multipart.MultipartFile;

public class Printed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.printed_id
     *
     * @mbggenerated
     */
    private Integer printedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.print_name
     *
     * @mbggenerated
     */
    private String printName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.print_num
     *
     * @mbggenerated
     */
    private String printNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.print_size
     *
     * @mbggenerated
     */
    private Integer printSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.print_picture
     *
     * @mbggenerated
     */
    private String printPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.print_picture
     *
     * @mbggenerated
     */
    private MultipartFile printPictureFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printed.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.printed_id
     *
     * @return the value of printed.printed_id
     *
     * @mbggenerated
     */
    public Integer getPrintedId() {
        return printedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.printed_id
     *
     * @param printedId the value for printed.printed_id
     *
     * @mbggenerated
     */
    public void setPrintedId(Integer printedId) {
        this.printedId = printedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.print_name
     *
     * @return the value of printed.print_name
     *
     * @mbggenerated
     */
    public String getPrintName() {
        return printName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.print_name
     *
     * @param printName the value for printed.print_name
     *
     * @mbggenerated
     */
    public void setPrintName(String printName) {
        this.printName = printName == null ? null : printName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.print_num
     *
     * @return the value of printed.print_num
     *
     * @mbggenerated
     */
    public String getPrintNum() {
        return printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.print_num
     *
     * @param printNum the value for printed.print_num
     *
     * @mbggenerated
     */
    public void setPrintNum(String printNum) {
        this.printNum = printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.print_size
     *
     * @return the value of printed.print_size
     *
     * @mbggenerated
     */
    public Integer getPrintSize() {
        return printSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.print_size
     *
     * @param printSize the value for printed.print_size
     *
     * @mbggenerated
     */
    public void setPrintSize(Integer printSize) {
        this.printSize = printSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.print_picture
     *
     * @return the value of printed.print_picture
     *
     * @mbggenerated
     */
    public String getPrintPicture() {
        return printPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.print_picture
     *
     * @param printPicture the value for printed.print_picture
     *
     * @mbggenerated
     */
    public void setPrintPicture(String printPicture) {
        this.printPicture = printPicture == null ? null : printPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printed.fake
     *
     * @return the value of printed.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printed.fake
     *
     * @param fake the value for printed.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    public MultipartFile getPrintPictureFile() {
        return printPictureFile;
    }

    public void setPrintPictureFile(MultipartFile printPictureFile) {
        this.printPictureFile = printPictureFile;
    }
}