package com.generator.pojo;

public class PurRejected {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.rejected_id
     *
     * @mbggenerated
     */
    private Integer rejectedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.batch_number
     *
     * @mbggenerated
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.supplier_name
     *
     * @mbggenerated
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.supper_spec
     *
     * @mbggenerated
     */
    private String supperSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.material_name
     *
     * @mbggenerated
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.pit_type
     *
     * @mbggenerated
     */
    private String pitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.blanking_size
     *
     * @mbggenerated
     */
    private String blankingSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.width_line
     *
     * @mbggenerated
     */
    private String widthLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.line_type
     *
     * @mbggenerated
     */
    private Integer lineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.pur_price
     *
     * @mbggenerated
     */
    private Double purPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.materials_number
     *
     * @mbggenerated
     */
    private Integer materialsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.rejected_num
     *
     * @mbggenerated
     */
    private Integer rejectedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.compensate_money
     *
     * @mbggenerated
     */
    private Double compensateMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.cause_of_return
     *
     * @mbggenerated
     */
    private String causeOfReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.rejected_remarks
     *
     * @mbggenerated
     */
    private String rejectedRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.registrant
     *
     * @mbggenerated
     */
    private String registrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.rejected_time
     *
     * @mbggenerated
     */
    private String rejectedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pur_rejected.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.rejected_id
     *
     * @return the value of pur_rejected.rejected_id
     *
     * @mbggenerated
     */
    public Integer getRejectedId() {
        return rejectedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.rejected_id
     *
     * @param rejectedId the value for pur_rejected.rejected_id
     *
     * @mbggenerated
     */
    public void setRejectedId(Integer rejectedId) {
        this.rejectedId = rejectedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.order_account
     *
     * @return the value of pur_rejected.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.order_account
     *
     * @param orderAccount the value for pur_rejected.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.batch_number
     *
     * @return the value of pur_rejected.batch_number
     *
     * @mbggenerated
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.batch_number
     *
     * @param batchNumber the value for pur_rejected.batch_number
     *
     * @mbggenerated
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber == null ? null : batchNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.supplier_name
     *
     * @return the value of pur_rejected.supplier_name
     *
     * @mbggenerated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.supplier_name
     *
     * @param supplierName the value for pur_rejected.supplier_name
     *
     * @mbggenerated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.supper_spec
     *
     * @return the value of pur_rejected.supper_spec
     *
     * @mbggenerated
     */
    public String getSupperSpec() {
        return supperSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.supper_spec
     *
     * @param supperSpec the value for pur_rejected.supper_spec
     *
     * @mbggenerated
     */
    public void setSupperSpec(String supperSpec) {
        this.supperSpec = supperSpec == null ? null : supperSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.material_name
     *
     * @return the value of pur_rejected.material_name
     *
     * @mbggenerated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.material_name
     *
     * @param materialName the value for pur_rejected.material_name
     *
     * @mbggenerated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.pit_type
     *
     * @return the value of pur_rejected.pit_type
     *
     * @mbggenerated
     */
    public String getPitType() {
        return pitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.pit_type
     *
     * @param pitType the value for pur_rejected.pit_type
     *
     * @mbggenerated
     */
    public void setPitType(String pitType) {
        this.pitType = pitType == null ? null : pitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.blanking_size
     *
     * @return the value of pur_rejected.blanking_size
     *
     * @mbggenerated
     */
    public String getBlankingSize() {
        return blankingSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.blanking_size
     *
     * @param blankingSize the value for pur_rejected.blanking_size
     *
     * @mbggenerated
     */
    public void setBlankingSize(String blankingSize) {
        this.blankingSize = blankingSize == null ? null : blankingSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.width_line
     *
     * @return the value of pur_rejected.width_line
     *
     * @mbggenerated
     */
    public String getWidthLine() {
        return widthLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.width_line
     *
     * @param widthLine the value for pur_rejected.width_line
     *
     * @mbggenerated
     */
    public void setWidthLine(String widthLine) {
        this.widthLine = widthLine == null ? null : widthLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.line_type
     *
     * @return the value of pur_rejected.line_type
     *
     * @mbggenerated
     */
    public Integer getLineType() {
        return lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.line_type
     *
     * @param lineType the value for pur_rejected.line_type
     *
     * @mbggenerated
     */
    public void setLineType(Integer lineType) {
        this.lineType = lineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.pur_price
     *
     * @return the value of pur_rejected.pur_price
     *
     * @mbggenerated
     */
    public Double getPurPrice() {
        return purPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.pur_price
     *
     * @param purPrice the value for pur_rejected.pur_price
     *
     * @mbggenerated
     */
    public void setPurPrice(Double purPrice) {
        this.purPrice = purPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.materials_number
     *
     * @return the value of pur_rejected.materials_number
     *
     * @mbggenerated
     */
    public Integer getMaterialsNumber() {
        return materialsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.materials_number
     *
     * @param materialsNumber the value for pur_rejected.materials_number
     *
     * @mbggenerated
     */
    public void setMaterialsNumber(Integer materialsNumber) {
        this.materialsNumber = materialsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.rejected_num
     *
     * @return the value of pur_rejected.rejected_num
     *
     * @mbggenerated
     */
    public Integer getRejectedNum() {
        return rejectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.rejected_num
     *
     * @param rejectedNum the value for pur_rejected.rejected_num
     *
     * @mbggenerated
     */
    public void setRejectedNum(Integer rejectedNum) {
        this.rejectedNum = rejectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.compensate_money
     *
     * @return the value of pur_rejected.compensate_money
     *
     * @mbggenerated
     */
    public Double getCompensateMoney() {
        return compensateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.compensate_money
     *
     * @param compensateMoney the value for pur_rejected.compensate_money
     *
     * @mbggenerated
     */
    public void setCompensateMoney(Double compensateMoney) {
        this.compensateMoney = compensateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.money
     *
     * @return the value of pur_rejected.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.money
     *
     * @param money the value for pur_rejected.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.cause_of_return
     *
     * @return the value of pur_rejected.cause_of_return
     *
     * @mbggenerated
     */
    public String getCauseOfReturn() {
        return causeOfReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.cause_of_return
     *
     * @param causeOfReturn the value for pur_rejected.cause_of_return
     *
     * @mbggenerated
     */
    public void setCauseOfReturn(String causeOfReturn) {
        this.causeOfReturn = causeOfReturn == null ? null : causeOfReturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.rejected_remarks
     *
     * @return the value of pur_rejected.rejected_remarks
     *
     * @mbggenerated
     */
    public String getRejectedRemarks() {
        return rejectedRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.rejected_remarks
     *
     * @param rejectedRemarks the value for pur_rejected.rejected_remarks
     *
     * @mbggenerated
     */
    public void setRejectedRemarks(String rejectedRemarks) {
        this.rejectedRemarks = rejectedRemarks == null ? null : rejectedRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.registrant
     *
     * @return the value of pur_rejected.registrant
     *
     * @mbggenerated
     */
    public String getRegistrant() {
        return registrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.registrant
     *
     * @param registrant the value for pur_rejected.registrant
     *
     * @mbggenerated
     */
    public void setRegistrant(String registrant) {
        this.registrant = registrant == null ? null : registrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.rejected_time
     *
     * @return the value of pur_rejected.rejected_time
     *
     * @mbggenerated
     */
    public String getRejectedTime() {
        return rejectedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.rejected_time
     *
     * @param rejectedTime the value for pur_rejected.rejected_time
     *
     * @mbggenerated
     */
    public void setRejectedTime(String rejectedTime) {
        this.rejectedTime = rejectedTime == null ? null : rejectedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pur_rejected.fake
     *
     * @return the value of pur_rejected.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pur_rejected.fake
     *
     * @param fake the value for pur_rejected.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}