package com.generator.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class ReceivableAdjustment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_id
     *
     * @mbggenerated
     */
    private Integer receivableAdjustmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_remarks
     *
     * @mbggenerated
     */
    private String receivableAdjustmentRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_date
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date receivableAdjustmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_price
     *
     * @mbggenerated
     */
    private Double receivableAdjustmentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_after_price
     *
     * @mbggenerated
     */
    private Double receivableAdjustmentAfterPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_total
     *
     * @mbggenerated
     */
    private Double receivableAdjustmentTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_after_total
     *
     * @mbggenerated
     */
    private Double receivableAdjustmentAfterTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.receivable_adjustment_type
     *
     * @mbggenerated
     */
    private Double receivableAdjustmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.order_account
     *
     * @mbggenerated
     */
    private String orderAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.custom_name
     *
     * @mbggenerated
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    private String cartonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    private int paymentRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    private int receiptRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    private String FinanceDate;

    private String financeRegisters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_id
     *
     * @return the value of receivable_adjustment.receivable_adjustment_id
     *
     * @mbggenerated
     */
    public Integer getReceivableAdjustmentId() {
        return receivableAdjustmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_id
     *
     * @param receivableAdjustmentId the value for receivable_adjustment.receivable_adjustment_id
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentId(Integer receivableAdjustmentId) {
        this.receivableAdjustmentId = receivableAdjustmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_remarks
     *
     * @return the value of receivable_adjustment.receivable_adjustment_remarks
     *
     * @mbggenerated
     */
    public String getReceivableAdjustmentRemarks() {
        return receivableAdjustmentRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_remarks
     *
     * @param receivableAdjustmentRemarks the value for receivable_adjustment.receivable_adjustment_remarks
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentRemarks(String receivableAdjustmentRemarks) {
        this.receivableAdjustmentRemarks = receivableAdjustmentRemarks == null ? null : receivableAdjustmentRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_date
     *
     * @return the value of receivable_adjustment.receivable_adjustment_date
     *
     * @mbggenerated
     */
    public Date getReceivableAdjustmentDate() {
        return receivableAdjustmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_date
     *
     * @param receivableAdjustmentDate the value for receivable_adjustment.receivable_adjustment_date
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentDate(Date receivableAdjustmentDate) {
        this.receivableAdjustmentDate = receivableAdjustmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_price
     *
     * @return the value of receivable_adjustment.receivable_adjustment_price
     *
     * @mbggenerated
     */
    public Double getReceivableAdjustmentPrice() {
        return receivableAdjustmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_price
     *
     * @param receivableAdjustmentPrice the value for receivable_adjustment.receivable_adjustment_price
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentPrice(Double receivableAdjustmentPrice) {
        this.receivableAdjustmentPrice = receivableAdjustmentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_after_price
     *
     * @return the value of receivable_adjustment.receivable_adjustment_after_price
     *
     * @mbggenerated
     */
    public Double getReceivableAdjustmentAfterPrice() {
        return receivableAdjustmentAfterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_after_price
     *
     * @param receivableAdjustmentAfterPrice the value for receivable_adjustment.receivable_adjustment_after_price
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentAfterPrice(Double receivableAdjustmentAfterPrice) {
        this.receivableAdjustmentAfterPrice = receivableAdjustmentAfterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_total
     *
     * @return the value of receivable_adjustment.receivable_adjustment_total
     *
     * @mbggenerated
     */
    public Double getReceivableAdjustmentTotal() {
        return receivableAdjustmentTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_total
     *
     * @param receivableAdjustmentTotal the value for receivable_adjustment.receivable_adjustment_total
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentTotal(Double receivableAdjustmentTotal) {
        this.receivableAdjustmentTotal = receivableAdjustmentTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_after_total
     *
     * @return the value of receivable_adjustment.receivable_adjustment_after_total
     *
     * @mbggenerated
     */
    public Double getReceivableAdjustmentAfterTotal() {
        return receivableAdjustmentAfterTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_after_total
     *
     * @param receivableAdjustmentAfterTotal the value for receivable_adjustment.receivable_adjustment_after_total
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentAfterTotal(Double receivableAdjustmentAfterTotal) {
        this.receivableAdjustmentAfterTotal = receivableAdjustmentAfterTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.receivable_adjustment_type
     *
     * @return the value of receivable_adjustment.receivable_adjustment_type
     *
     * @mbggenerated
     */
    public Double getReceivableAdjustmentType() {
        return receivableAdjustmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.receivable_adjustment_type
     *
     * @param receivableAdjustmentType the value for receivable_adjustment.receivable_adjustment_type
     *
     * @mbggenerated
     */
    public void setReceivableAdjustmentType(Double receivableAdjustmentType) {
        this.receivableAdjustmentType = receivableAdjustmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.order_account
     *
     * @return the value of receivable_adjustment.order_account
     *
     * @mbggenerated
     */
    public String getOrderAccount() {
        return orderAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.order_account
     *
     * @param orderAccount the value for receivable_adjustment.order_account
     *
     * @mbggenerated
     */
    public void setOrderAccount(String orderAccount) {
        this.orderAccount = orderAccount == null ? null : orderAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.custom_name
     *
     * @return the value of receivable_adjustment.custom_name
     *
     * @mbggenerated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.custom_name
     *
     * @param customName the value for receivable_adjustment.custom_name
     *
     * @mbggenerated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivable_adjustment.carton_name
     *
     * @return cartonName the value of receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    public String getCartonName() {
        return cartonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivable_adjustment.carton_name
     *
     * @param cartonName the value for receivable_adjustment.carton_name
     *
     * @mbggenerated
     */
    public void setCartonName(String cartonName) {
        this.cartonName = cartonName == null ? null : cartonName.trim();
    }

    public int getPaymentRecordId() {
        return paymentRecordId;
    }

    public void setPaymentRecordId(int paymentRecordId) {
        this.paymentRecordId = paymentRecordId;
    }

    public int getReceiptRecordId() {
        return receiptRecordId;
    }

    public void setReceiptRecordId(int receiptRecordId) {
        this.receiptRecordId = receiptRecordId;
    }

    public String getFinanceDate() {
        return FinanceDate;
    }

    public void setFinanceDate(String financeDate) {
        FinanceDate = financeDate;
    }

    public String getFinanceRegisters() {
        return financeRegisters;
    }

    public void setFinanceRegisters(String financeRegisters) {
        this.financeRegisters = financeRegisters;
    }
}