package com.generator.pojo;

public class StaffTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_id
     *
     * @mbggenerated
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_number
     *
     * @mbggenerated
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_name
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_age
     *
     * @mbggenerated
     */
    private Integer staffAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_tel
     *
     * @mbggenerated
     */
    private String staffTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_address
     *
     * @mbggenerated
     */
    private String staffAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_post
     *
     * @mbggenerated
     */
    private String staffPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_salary
     *
     * @mbggenerated
     */
    private String staffSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.is_Salesman
     *
     * @mbggenerated
     */
    private Integer isSalesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.extract
     *
     * @mbggenerated
     */
    private Double extract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.staff_time
     *
     * @mbggenerated
     */
    private String staffTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.home_address
     *
     * @mbggenerated
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.open_bank
     *
     * @mbggenerated
     */
    private String openBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.mode
     *
     * @mbggenerated
     */
    private String mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_table.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_id
     *
     * @return the value of staff_table.staff_id
     *
     * @mbggenerated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_id
     *
     * @param staffId the value for staff_table.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_number
     *
     * @return the value of staff_table.staff_number
     *
     * @mbggenerated
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_number
     *
     * @param staffNumber the value for staff_table.staff_number
     *
     * @mbggenerated
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_name
     *
     * @return the value of staff_table.staff_name
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_name
     *
     * @param staffName the value for staff_table.staff_name
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_age
     *
     * @return the value of staff_table.staff_age
     *
     * @mbggenerated
     */
    public Integer getStaffAge() {
        return staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_age
     *
     * @param staffAge the value for staff_table.staff_age
     *
     * @mbggenerated
     */
    public void setStaffAge(Integer staffAge) {
        this.staffAge = staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_tel
     *
     * @return the value of staff_table.staff_tel
     *
     * @mbggenerated
     */
    public String getStaffTel() {
        return staffTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_tel
     *
     * @param staffTel the value for staff_table.staff_tel
     *
     * @mbggenerated
     */
    public void setStaffTel(String staffTel) {
        this.staffTel = staffTel == null ? null : staffTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_address
     *
     * @return the value of staff_table.staff_address
     *
     * @mbggenerated
     */
    public String getStaffAddress() {
        return staffAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_address
     *
     * @param staffAddress the value for staff_table.staff_address
     *
     * @mbggenerated
     */
    public void setStaffAddress(String staffAddress) {
        this.staffAddress = staffAddress == null ? null : staffAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_post
     *
     * @return the value of staff_table.staff_post
     *
     * @mbggenerated
     */
    public String getStaffPost() {
        return staffPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_post
     *
     * @param staffPost the value for staff_table.staff_post
     *
     * @mbggenerated
     */
    public void setStaffPost(String staffPost) {
        this.staffPost = staffPost == null ? null : staffPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_salary
     *
     * @return the value of staff_table.staff_salary
     *
     * @mbggenerated
     */
    public String getStaffSalary() {
        return staffSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_salary
     *
     * @param staffSalary the value for staff_table.staff_salary
     *
     * @mbggenerated
     */
    public void setStaffSalary(String staffSalary) {
        this.staffSalary = staffSalary == null ? null : staffSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.is_Salesman
     *
     * @return the value of staff_table.is_Salesman
     *
     * @mbggenerated
     */
    public Integer getIsSalesman() {
        return isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.is_Salesman
     *
     * @param isSalesman the value for staff_table.is_Salesman
     *
     * @mbggenerated
     */
    public void setIsSalesman(Integer isSalesman) {
        this.isSalesman = isSalesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.extract
     *
     * @return the value of staff_table.extract
     *
     * @mbggenerated
     */
    public Double getExtract() {
        return extract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.extract
     *
     * @param extract the value for staff_table.extract
     *
     * @mbggenerated
     */
    public void setExtract(Double extract) {
        this.extract = extract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.staff_time
     *
     * @return the value of staff_table.staff_time
     *
     * @mbggenerated
     */
    public String getStaffTime() {
        return staffTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.staff_time
     *
     * @param staffTime the value for staff_table.staff_time
     *
     * @mbggenerated
     */
    public void setStaffTime(String staffTime) {
        this.staffTime = staffTime == null ? null : staffTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.fake
     *
     * @return the value of staff_table.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.fake
     *
     * @param fake the value for staff_table.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.sex
     *
     * @return the value of staff_table.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.sex
     *
     * @param sex the value for staff_table.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.nation
     *
     * @return the value of staff_table.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.nation
     *
     * @param nation the value for staff_table.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.id_number
     *
     * @return the value of staff_table.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.id_number
     *
     * @param idNumber the value for staff_table.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.home_address
     *
     * @return the value of staff_table.home_address
     *
     * @mbggenerated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.home_address
     *
     * @param homeAddress the value for staff_table.home_address
     *
     * @mbggenerated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.open_bank
     *
     * @return the value of staff_table.open_bank
     *
     * @mbggenerated
     */
    public String getOpenBank() {
        return openBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.open_bank
     *
     * @param openBank the value for staff_table.open_bank
     *
     * @mbggenerated
     */
    public void setOpenBank(String openBank) {
        this.openBank = openBank == null ? null : openBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.account
     *
     * @return the value of staff_table.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.account
     *
     * @param account the value for staff_table.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.mode
     *
     * @return the value of staff_table.mode
     *
     * @mbggenerated
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.mode
     *
     * @param mode the value for staff_table.mode
     *
     * @mbggenerated
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_table.remarks
     *
     * @return the value of staff_table.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_table.remarks
     *
     * @param remarks the value for staff_table.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}