package com.generator.pojo;

public class SupplierMateriala {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.material_texture
     *
     * @mbggenerated
     */
    private String materialTexture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.material_code
     *
     * @mbggenerated
     */
    private String materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.my_code
     *
     * @mbggenerated
     */
    private String myCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.special_price
     *
     * @mbggenerated
     */
    private Double specialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialA.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    public String getFluteType() {
        return fluteType;
    }

    public void setFluteType(String fluteType) {
        this.fluteType = fluteType;
    }

    private String fluteType;//楞型


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.id
     *
     * @return the value of supplier_materialA.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.id
     *
     * @param id the value for supplier_materialA.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.supplier_id
     *
     * @return the value of supplier_materialA.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.supplier_id
     *
     * @param supplierId the value for supplier_materialA.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.material_texture
     *
     * @return the value of supplier_materialA.material_texture
     *
     * @mbggenerated
     */
    public String getMaterialTexture() {
        return materialTexture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.material_texture
     *
     * @param materialTexture the value for supplier_materialA.material_texture
     *
     * @mbggenerated
     */
    public void setMaterialTexture(String materialTexture) {
        this.materialTexture = materialTexture == null ? null : materialTexture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.material_code
     *
     * @return the value of supplier_materialA.material_code
     *
     * @mbggenerated
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.material_code
     *
     * @param materialCode the value for supplier_materialA.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.my_code
     *
     * @return the value of supplier_materialA.my_code
     *
     * @mbggenerated
     */
    public String getMyCode() {
        return myCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.my_code
     *
     * @param myCode the value for supplier_materialA.my_code
     *
     * @mbggenerated
     */
    public void setMyCode(String myCode) {
        this.myCode = myCode == null ? null : myCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.special_price
     *
     * @return the value of supplier_materialA.special_price
     *
     * @mbggenerated
     */
    public Double getSpecialPrice() {
        return specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.special_price
     *
     * @param specialPrice the value for supplier_materialA.special_price
     *
     * @mbggenerated
     */
    public void setSpecialPrice(Double specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialA.fake
     *
     * @return the value of supplier_materialA.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialA.fake
     *
     * @param fake the value for supplier_materialA.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}