package com.generator.pojo;

public class SupplierMaterialb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.supplier_id
     *
     * @mbggenerated
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.material_texture
     *
     * @mbggenerated
     */
    private String materialTexture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.square_price
     *
     * @mbggenerated
     */
    private Double squarePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.material_code
     *
     * @mbggenerated
     */
    private String materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.my_code
     *
     * @mbggenerated
     */
    private String myCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.material_price
     *
     * @mbggenerated
     */
    private Double materialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.special_offer
     *
     * @mbggenerated
     */
    private Double specialOffer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materialB.fake
     *
     * @mbggenerated
     */
    private Integer fake;


    public String getFluteType() {
        return fluteType;
    }

    public void setFluteType(String fluteType) {
        this.fluteType = fluteType;
    }

    private String fluteType;//楞型
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.id
     *
     * @return the value of supplier_materialB.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.id
     *
     * @param id the value for supplier_materialB.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.supplier_id
     *
     * @return the value of supplier_materialB.supplier_id
     *
     * @mbggenerated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.supplier_id
     *
     * @param supplierId the value for supplier_materialB.supplier_id
     *
     * @mbggenerated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.material_texture
     *
     * @return the value of supplier_materialB.material_texture
     *
     * @mbggenerated
     */
    public String getMaterialTexture() {
        return materialTexture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.material_texture
     *
     * @param materialTexture the value for supplier_materialB.material_texture
     *
     * @mbggenerated
     */
    public void setMaterialTexture(String materialTexture) {
        this.materialTexture = materialTexture == null ? null : materialTexture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.square_price
     *
     * @return the value of supplier_materialB.square_price
     *
     * @mbggenerated
     */
    public Double getSquarePrice() {
        return squarePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.square_price
     *
     * @param squarePrice the value for supplier_materialB.square_price
     *
     * @mbggenerated
     */
    public void setSquarePrice(Double squarePrice) {
        this.squarePrice = squarePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.material_code
     *
     * @return the value of supplier_materialB.material_code
     *
     * @mbggenerated
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.material_code
     *
     * @param materialCode the value for supplier_materialB.material_code
     *
     * @mbggenerated
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.my_code
     *
     * @return the value of supplier_materialB.my_code
     *
     * @mbggenerated
     */
    public String getMyCode() {
        return myCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.my_code
     *
     * @param myCode the value for supplier_materialB.my_code
     *
     * @mbggenerated
     */
    public void setMyCode(String myCode) {
        this.myCode = myCode == null ? null : myCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.material_price
     *
     * @return the value of supplier_materialB.material_price
     *
     * @mbggenerated
     */
    public Double getMaterialPrice() {
        return materialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.material_price
     *
     * @param materialPrice the value for supplier_materialB.material_price
     *
     * @mbggenerated
     */
    public void setMaterialPrice(Double materialPrice) {
        this.materialPrice = materialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.special_offer
     *
     * @return the value of supplier_materialB.special_offer
     *
     * @mbggenerated
     */
    public Double getSpecialOffer() {
        return specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.special_offer
     *
     * @param specialOffer the value for supplier_materialB.special_offer
     *
     * @mbggenerated
     */
    public void setSpecialOffer(Double specialOffer) {
        this.specialOffer = specialOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materialB.fake
     *
     * @return the value of supplier_materialB.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materialB.fake
     *
     * @param fake the value for supplier_materialB.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}