package com.generator.pojo;

public class TicketProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_product_id
     *
     * @mbggenerated
     */
    private Integer ticketProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_id
     *
     * @mbggenerated
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_product_name
     *
     * @mbggenerated
     */
    private String ticketProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_spec_model
     *
     * @mbggenerated
     */
    private String ticketSpecModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_unit
     *
     * @mbggenerated
     */
    private String ticketUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_price
     *
     * @mbggenerated
     */
    private Double ticketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_num
     *
     * @mbggenerated
     */
    private Integer ticketNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_product_money
     *
     * @mbggenerated
     */
    private Double ticketProductMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_rate
     *
     * @mbggenerated
     */
    private String ticketRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.ticket_rate_amount
     *
     * @mbggenerated
     */
    private Double ticketRateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_product.fake
     *
     * @mbggenerated
     */
    private Integer fake;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_product_id
     *
     * @return the value of ticket_product.ticket_product_id
     *
     * @mbggenerated
     */
    public Integer getTicketProductId() {
        return ticketProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_product_id
     *
     * @param ticketProductId the value for ticket_product.ticket_product_id
     *
     * @mbggenerated
     */
    public void setTicketProductId(Integer ticketProductId) {
        this.ticketProductId = ticketProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_id
     *
     * @return the value of ticket_product.ticket_id
     *
     * @mbggenerated
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_id
     *
     * @param ticketId the value for ticket_product.ticket_id
     *
     * @mbggenerated
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_product_name
     *
     * @return the value of ticket_product.ticket_product_name
     *
     * @mbggenerated
     */
    public String getTicketProductName() {
        return ticketProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_product_name
     *
     * @param ticketProductName the value for ticket_product.ticket_product_name
     *
     * @mbggenerated
     */
    public void setTicketProductName(String ticketProductName) {
        this.ticketProductName = ticketProductName == null ? null : ticketProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_spec_model
     *
     * @return the value of ticket_product.ticket_spec_model
     *
     * @mbggenerated
     */
    public String getTicketSpecModel() {
        return ticketSpecModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_spec_model
     *
     * @param ticketSpecModel the value for ticket_product.ticket_spec_model
     *
     * @mbggenerated
     */
    public void setTicketSpecModel(String ticketSpecModel) {
        this.ticketSpecModel = ticketSpecModel == null ? null : ticketSpecModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_unit
     *
     * @return the value of ticket_product.ticket_unit
     *
     * @mbggenerated
     */
    public String getTicketUnit() {
        return ticketUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_unit
     *
     * @param ticketUnit the value for ticket_product.ticket_unit
     *
     * @mbggenerated
     */
    public void setTicketUnit(String ticketUnit) {
        this.ticketUnit = ticketUnit == null ? null : ticketUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_price
     *
     * @return the value of ticket_product.ticket_price
     *
     * @mbggenerated
     */
    public Double getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_price
     *
     * @param ticketPrice the value for ticket_product.ticket_price
     *
     * @mbggenerated
     */
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_num
     *
     * @return the value of ticket_product.ticket_num
     *
     * @mbggenerated
     */
    public Integer getTicketNum() {
        return ticketNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_num
     *
     * @param ticketNum the value for ticket_product.ticket_num
     *
     * @mbggenerated
     */
    public void setTicketNum(Integer ticketNum) {
        this.ticketNum = ticketNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_product_money
     *
     * @return the value of ticket_product.ticket_product_money
     *
     * @mbggenerated
     */
    public Double getTicketProductMoney() {
        return ticketProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_product_money
     *
     * @param ticketProductMoney the value for ticket_product.ticket_product_money
     *
     * @mbggenerated
     */
    public void setTicketProductMoney(Double ticketProductMoney) {
        this.ticketProductMoney = ticketProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_rate
     *
     * @return the value of ticket_product.ticket_rate
     *
     * @mbggenerated
     */
    public String getTicketRate() {
        return ticketRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_rate
     *
     * @param ticketRate the value for ticket_product.ticket_rate
     *
     * @mbggenerated
     */
    public void setTicketRate(String ticketRate) {
        this.ticketRate = ticketRate == null ? null : ticketRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.ticket_rate_amount
     *
     * @return the value of ticket_product.ticket_rate_amount
     *
     * @mbggenerated
     */
    public Double getTicketRateAmount() {
        return ticketRateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.ticket_rate_amount
     *
     * @param ticketRateAmount the value for ticket_product.ticket_rate_amount
     *
     * @mbggenerated
     */
    public void setTicketRateAmount(Double ticketRateAmount) {
        this.ticketRateAmount = ticketRateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_product.fake
     *
     * @return the value of ticket_product.fake
     *
     * @mbggenerated
     */
    public Integer getFake() {
        return fake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_product.fake
     *
     * @param fake the value for ticket_product.fake
     *
     * @mbggenerated
     */
    public void setFake(Integer fake) {
        this.fake = fake;
    }
}